-- Auto-generated by scraper
WishListData_Rogue = {
    ASSASSINATION = {
        icon = "Interface/ICONS/Ability_Rogue_DeadlyBrew",
        talent = "CMQAAAAAAAAAAAAAAAAAAAAAAYmZMzMmBAAAAAAYWmxsMDAAAAAAttMzMYmBzMzysNYMmZmZmZmZYzyYGgNzyADYBsNMBGWGA",
        statprio = "Mastery > Crit > Haste > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "19.8%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "84.9%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "63.2%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "66.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "86.2%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "49.5%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "57.2%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "68.2%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "74.1%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "2.8%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "58.5%" },
            { id = 213491, name = "Deadly Onyx", popularity = "58.4%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "28.9%" },
            { id = 213482, name = "Masterful Emerald", popularity = "24.7%" }
        },
        HEAD = {
            { id = 237664, name = "BiSHood of the Sudden Eclipse", popularity = "36.0%" },
            { id = 229289, name = "Spectral Gambler's Damned Visage", popularity = "35.0%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "6.7%" },
            { id = 221163, name = "Whispering Mask", popularity = "5.4%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "4.7%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "28.2%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "19.3%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "9.0%" },
            { id = 185842, name = "BiSOrnately Engraved Amplifier", popularity = "7.3%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "7.0%" }
        },
        SHOULDERS = {
            { id = 229287, name = "Spectral Gambler's Bladed Mantle", popularity = "44.3%" },
            { id = 237662, name = "BiSSmokemantle of the Sudden Eclipse", popularity = "30.5%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "5.2%" },
            { id = 242486, name = "Mantle of Wounded Fate", popularity = "4.9%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "3.0%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.8%" }
        },
        CHEST = {
            { id = 229292, name = "Spectral Gambler's Vest", popularity = "40.1%" },
            { id = 237667, name = "BiSTactical Vest of the Sudden Eclipse", popularity = "29.0%" },
            { id = 246273, name = "Vest of Refracted Shadows", popularity = "6.5%" },
            { id = 242482, name = "Reinforced Stalkerhide Vest", popularity = "4.7%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "4.3%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "32.8%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "18.6%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "13.6%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "6.1%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "5.7%" }
        },
        HANDS = {
            { id = 229290, name = "Spectral Gambler's Gloves", popularity = "43.2%" },
            { id = 237665, name = "BiSDeathgrips of the Sudden Eclipse", popularity = "30.4%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "6.1%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "2.5%" },
            { id = 243510, name = "Wastelander Scout's Grips", popularity = "1.6%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "90.5%" },
            { id = 221134, name = "Shadow Congregant's Belt", popularity = "1.8%" },
            { id = 237533, name = "BiSAtomic Phasebelt", popularity = "1.1%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "0.9%" },
            { id = 237557, name = "Reaper's Dreadbelt", popularity = "0.6%" }
        },
        LEGS = {
            { id = 229288, name = "Spectral Gambler's Pantaloons", popularity = "41.7%" },
            { id = 237663, name = "BiSPants of the Sudden Eclipse", popularity = "34.8%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "5.6%" },
            { id = 242473, name = "Spittle-Stained Trousers", popularity = "4.7%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "3.0%" }
        },
        FEET = {
            { id = 219327, name = "Rune-Branded Kickers", popularity = "16.4%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "13.9%" },
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "12.0%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "10.6%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "9.6%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "47.1%" },
            { id = 221200, name = "BiSRadiant Necromancer's Band", popularity = "17.6%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "16.4%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "13.4%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "11.2%" }
        },
        MAIN_HAND = {
            { id = 222438, name = "BiSEverforged Stabber", popularity = "68.7%" },
            { id = 243535, name = "Wastelander's Gilded Stiletto", popularity = "4.3%" },
            { id = 237729, name = "Prodigious Gene Splicer", popularity = "3.4%" },
            { id = 234493, name = "Geezle's Coercive Volt-ohmmeter", popularity = "3.1%" },
            { id = 221138, name = "Parson's Ornamented Blade", popularity = "2.4%" }
        },
        OFF_HAND = {
            { id = 222438, name = "BiSEverforged Stabber", popularity = "17.9%" },
            { id = 237729, name = "Prodigious Gene Splicer", popularity = "12.9%" },
            { id = 243535, name = "Wastelander's Gilded Stiletto", popularity = "10.1%" },
            { id = 234493, name = "Geezle's Coercive Volt-ohmmeter", popularity = "9.8%" },
            { id = 237740, name = "BiSVengeful Netherspike", popularity = "7.8%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "52.0%" },
            { id = 219308, name = "Signet of the Priory", popularity = "32.1%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "24.3%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "12.9%" },
            { id = 230027, name = "House of Cards", popularity = "12.0%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "65.1%" },
            { id = 212265, name = "Tempered Potion", popularity = "69.2%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "12.2%" },
            { id = 222504, name = "Ironclaw Whetstone", popularity = "65.9%" }
        }
    },
    OUTLAW = {
        icon = "Interface/ICONS/Ability_Rogue_SinisterCalling",
        talent = "CQQAAAAAAAAAAAAAAAAAAAAAAAAM2mBjZGzMzYYGegxMzMMzMz0yMmtZAAAAAAw2yMzgZmZWglZbAAAAYmZAwY2MMwAzCL0CbGA",
        statprio = "Vers > Haste > Crit > Mastery",
        enchants = {
            HEAD = { id = 238405, name = "Greater Rune of Twilight Devastation", popularity = "45.5%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "87.4%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "55.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "66.3%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "86.7%" },
            RINGS = { id = 223796, name = "Cursed Versatility", popularity = "44.8%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.0%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "58.5%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "80.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "2.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213485, name = "Versatile Emerald", popularity = "60.1%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "59.3%" },
            { id = 213470, name = "Quick Sapphire", popularity = "47.9%" },
            { id = 213461, name = "Versatile Ruby", popularity = "45.9%" }
        },
        HEAD = {
            { id = 229289, name = "Spectral Gambler's Damned Visage", popularity = "69.4%" },
            { id = 237664, name = "BiSHood of the Sudden Eclipse", popularity = "20.2%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.9%" },
            { id = 221163, name = "Whispering Mask", popularity = "1.0%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "0.9%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "42.0%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "19.1%" },
            { id = 237568, name = "BiSChrysalis of Sundered Souls", popularity = "10.3%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "6.2%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "6.1%" }
        },
        SHOULDERS = {
            { id = 229287, name = "Spectral Gambler's Bladed Mantle", popularity = "54.8%" },
            { id = 237662, name = "BiSSmokemantle of the Sudden Eclipse", popularity = "23.2%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "7.6%" },
            { id = 242486, name = "Mantle of Wounded Fate", popularity = "2.7%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "1.7%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.7%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "0.1%" }
        },
        CHEST = {
            { id = 229292, name = "Spectral Gambler's Vest", popularity = "33.1%" },
            { id = 237667, name = "BiSTactical Vest of the Sudden Eclipse", popularity = "27.7%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "16.0%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "7.6%" },
            { id = 242482, name = "Reinforced Stalkerhide Vest", popularity = "3.2%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "43.8%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "9.1%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "7.1%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "5.9%" },
            { id = 237546, name = "Bindings of Lost Essence", popularity = "5.1%" }
        },
        HANDS = {
            { id = 229290, name = "Spectral Gambler's Gloves", popularity = "69.3%" },
            { id = 237665, name = "Deathgrips of the Sudden Eclipse", popularity = "12.3%" },
            { id = 178832, name = "BiSGloves of Haunting Fixation", popularity = "6.0%" },
            { id = 237975, name = "Void-Scarred Blade's Grips", popularity = "1.3%" },
            { id = 237540, name = "Winged Gamma Handlers", popularity = "1.2%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "90.8%" },
            { id = 185809, name = "Venza's Powderbelt", popularity = "1.0%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "1.0%" },
            { id = 221058, name = "Brewery Toiler's Waistband", popularity = "0.6%" },
            { id = 238027, name = "Harvested Creephide Cord", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229288, name = "Spectral Gambler's Pantaloons", popularity = "59.6%" },
            { id = 237663, name = "BiSPants of the Sudden Eclipse", popularity = "21.2%" },
            { id = 228854, name = "Bilgerat's Discarded Slacks", popularity = "2.7%" },
            { id = 185801, name = "Anomalous Starlit Breeches", popularity = "2.0%" },
            { id = 221042, name = "Squallrider's Kilt", popularity = "1.5%" }
        },
        FEET = {
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "23.3%" },
            { id = 229291, name = "Spectral Gambler's Cavaliers", popularity = "21.9%" },
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "9.6%" },
            { id = 219327, name = "Rune-Branded Kickers", popularity = "8.7%" },
            { id = 228876, name = "Dragster's Last Stride", popularity = "6.5%" }
        },
        FINGER1 = {
            { id = 215135, name = "BiSRing of Earthen Craftsmanship", popularity = "70.9%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "20.8%" },
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "13.9%" },
            { id = 228843, name = "Miniature Roulette Wheel", popularity = "8.7%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "7.0%" }
        },
        MAIN_HAND = {
            { id = 222440, name = "Everforged Longsword", popularity = "47.8%" },
            { id = 221144, name = "Zephyrous Sail Carver", popularity = "7.2%" },
            { id = 221128, name = "Starforged Seraph's Mace", popularity = "5.7%" },
            { id = 232804, name = "Capo's Molten Knuckles", popularity = "5.6%" },
            { id = 228904, name = "Crowd Favorite", popularity = "2.9%" }
        },
        OFF_HAND = {
            { id = 237780, name = "Nightfall Curseblade's Cudgel", popularity = "35.7%" },
            { id = 232804, name = "Capo's Molten Knuckles", popularity = "9.0%" },
            { id = 221144, name = "Zephyrous Sail Carver", popularity = "7.3%" },
            { id = 222438, name = "Everforged Stabber", popularity = "6.0%" },
            { id = 221128, name = "Starforged Seraph's Mace", popularity = "5.0%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "43.3%" },
            { id = 242495, name = "Incorporeal Warpclaw", popularity = "24.9%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "20.8%" },
            { id = 242397, name = "BiSSigil of the Cosmic Hunt", popularity = "15.6%" },
            { id = 230197, name = "Geargrinder's Spare Keys", popularity = "13.3%" }
        },
        consumables = {
            { id = 212277, name = "Flask of Tempered Versatility", popularity = "76.7%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "32.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "62.3%" },
            { id = 222720, name = "The Sushi Special", popularity = "36.6%" },
            { id = 222504, name = "Ironclaw Whetstone", popularity = "32.2%" },
            { id = 222510, name = "Ironclaw Weightstone", popularity = "32.2%" }
        }
    },
    SUBTLETY = {
        icon = "Interface/ICONS/Ability_Stealth",
        talent = "CUQAAAAAAAAAAAAAAAAAAAAAAAAM2mBAAAAAgZZMWmGzgZmxYMjxMzMMmtZxYstNzMYmxYMzysNAAAAMDGAjZzwADMLsQL2gB",
        statprio = "Mastery > Vers > Crit > Haste",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "14.9%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "87.2%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "58.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "60.8%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "89.4%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "47.2%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.1%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "38.4%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "78.2%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "2.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213497, name = "Versatile Onyx", popularity = "60.1%" },
            { id = 213473, name = "Masterful Sapphire", popularity = "56.8%" },
            { id = 213458, name = "Masterful Ruby", popularity = "32.1%" },
            { id = 213491, name = "Deadly Onyx", popularity = "28.3%" }
        },
        HEAD = {
            { id = 237664, name = "BiSHood of the Sudden Eclipse", popularity = "44.7%" },
            { id = 229289, name = "Spectral Gambler's Damned Visage", popularity = "36.4%" },
            { id = 221163, name = "Whispering Mask", popularity = "5.2%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "3.7%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.5%" }
        },
        NECK = {
            { id = 215136, name = "BiSAmulet of Earthen Craftsmanship", popularity = "35.0%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "29.9%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "15.6%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "4.5%" },
            { id = 237962, name = "Void-Scarred Choker", popularity = "1.5%" }
        },
        SHOULDERS = {
            { id = 229287, name = "Spectral Gambler's Bladed Mantle", popularity = "41.9%" },
            { id = 237662, name = "Smokemantle of the Sudden Eclipse", popularity = "29.7%" },
            { id = 237552, name = "BiSDeathbound Shoulderpads", popularity = "6.6%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "3.8%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "3.2%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.6%" }
        },
        CHEST = {
            { id = 229292, name = "Spectral Gambler's Vest", popularity = "40.6%" },
            { id = 237667, name = "BiSTactical Vest of the Sudden Eclipse", popularity = "39.0%" },
            { id = 242482, name = "Reinforced Stalkerhide Vest", popularity = "5.3%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "2.5%" },
            { id = 246273, name = "Vest of Refracted Shadows", popularity = "2.4%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "34.6%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "21.5%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "8.7%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "7.6%" },
            { id = 228885, name = "Hustler's Ante-Uppers", popularity = "5.4%" }
        },
        HANDS = {
            { id = 237665, name = "BiSDeathgrips of the Sudden Eclipse", popularity = "40.2%" },
            { id = 229290, name = "Spectral Gambler's Gloves", popularity = "19.1%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "7.4%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "6.3%" },
            { id = 228863, name = "Enforcer's Sticky Fingers", popularity = "5.9%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "90.9%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "1.9%" },
            { id = 237533, name = "Atomic Phasebelt", popularity = "1.0%" },
            { id = 237557, name = "BiSReaper's Dreadbelt", popularity = "0.8%" },
            { id = 221134, name = "Shadow Congregant's Belt", popularity = "0.6%" }
        },
        LEGS = {
            { id = 237663, name = "BiSPants of the Sudden Eclipse", popularity = "46.5%" },
            { id = 229288, name = "Spectral Gambler's Pantaloons", popularity = "38.3%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "3.8%" },
            { id = 242473, name = "Spittle-Stained Trousers", popularity = "2.3%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "1.3%" }
        },
        FEET = {
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "17.1%" },
            { id = 219327, name = "Rune-Branded Kickers", popularity = "16.9%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "16.4%" },
            { id = 237565, name = "Kinetic Dunerunners", popularity = "7.5%" },
            { id = 243041, name = "Umbral Stalker's Footpads", popularity = "6.3%" }
        },
        FINGER1 = {
            { id = 221200, name = "Radiant Necromancer's Band", popularity = "37.5%" },
            { id = 231265, name = "The Jastor Diamond", popularity = "36.1%" },
            { id = 221141, name = "BiSHigh Nerubian Signet", popularity = "25.0%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "24.0%" },
            { id = 178870, name = "Ritual Bone Band", popularity = "11.7%" }
        },
        MAIN_HAND = {
            { id = 222438, name = "Everforged Stabber", popularity = "63.8%" },
            { id = 237729, name = "BiSProdigious Gene Splicer", popularity = "6.2%" },
            { id = 243535, name = "Wastelander's Gilded Stiletto", popularity = "4.3%" },
            { id = 234493, name = "Geezle's Coercive Volt-ohmmeter", popularity = "4.1%" },
            { id = 228897, name = "Pyrotechnic Needle-Dropper", popularity = "3.7%" }
        },
        OFF_HAND = {
            { id = 237729, name = "BiSProdigious Gene Splicer", popularity = "22.3%" },
            { id = 222438, name = "Everforged Stabber", popularity = "13.4%" },
            { id = 228897, name = "Pyrotechnic Needle-Dropper", popularity = "10.6%" },
            { id = 221138, name = "Parson's Ornamented Blade", popularity = "9.1%" },
            { id = 234493, name = "Geezle's Coercive Volt-ohmmeter", popularity = "7.3%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "50.9%" },
            { id = 230027, name = "House of Cards", popularity = "31.1%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "27.7%" },
            { id = 242396, name = "BiSUnyielding Netherprism", popularity = "20.6%" },
            { id = 219312, name = "Empowering Crystal of Anub'ikkaj", popularity = "7.7%" }
        },
        consumables = {
            { id = 212277, name = "Flask of Tempered Versatility", popularity = "42.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "72.2%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "11.4%" },
            { id = 222504, name = "Ironclaw Whetstone", popularity = "74.9%" }
        }
    }
}
