-- Auto-generated by scraper
WishListData_Druid = {
    BALANCE = {
        icon = "Interface/ICONS/Spell_Nature_StarFall",
        talent = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALUmtmxYmBYWYZmZWYYsYWmZZmZbmZmZmZxsMGGshFGgxy2MbYMbDgJAAAALmZMAbGGD",
        statprio = "Mastery > Haste > Vers > Crit",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "60.6%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "77.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "67.2%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "58.7%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "59.2%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "27.2%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "58.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "9.6%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "1.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "58.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "9.6%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "1.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        HEAD = {
            { id = 237682, name = "BiSSkymane of the Mother Eagle", popularity = "85.5%" },
            { id = 229307, name = "Branches of Reclaiming Blight", popularity = "3.2%" },
            { id = 221163, name = "Whispering Mask", popularity = "1.4%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "1.2%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.0%" }
        },
        NECK = {
            { id = 178827, name = "BiSSin Stained Pendant", popularity = "41.6%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "13.8%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "10.5%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "6.8%" },
            { id = 237569, name = "Duskblaze's Desperation", popularity = "4.5%" }
        },
        SHOULDERS = {
            { id = 237680, name = "BiSRitual Pauldrons of the Mother Eagle", popularity = "75.9%" },
            { id = 237552, name = "Deathbound Shoulderpads", popularity = "4.3%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "4.1%" },
            { id = 185802, name = "Breakbeat Shoulderguards", popularity = "2.8%" },
            { id = 229305, name = "Jaws of Reclaiming Blight", popularity = "2.6%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.3%" }
        },
        CHEST = {
            { id = 237685, name = "BiSVest of the Mother Eagle", popularity = "87.6%" },
            { id = 229310, name = "Robes of Reclaiming Blight", popularity = "2.3%" },
            { id = 246273, name = "Vest of Refracted Shadows", popularity = "1.2%" },
            { id = 185786, name = "So'azmi's Fractal Vest", popularity = "1.1%" },
            { id = 242482, name = "Reinforced Stalkerhide Vest", popularity = "1.1%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "64.2%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "11.5%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "4.1%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "3.9%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "2.6%" }
        },
        HANDS = {
            { id = 237683, name = "BiSWings of the Mother Eagle", popularity = "79.6%" },
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "3.4%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "2.9%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "2.6%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "2.0%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "55.7%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "16.8%" },
            { id = 237533, name = "BiSAtomic Phasebelt", popularity = "8.0%" },
            { id = 221134, name = "Shadow Congregant's Belt", popularity = "3.9%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "3.9%" }
        },
        LEGS = {
            { id = 237681, name = "Breeches of the Mother Eagle", popularity = "57.2%" },
            { id = 242473, name = "BiSSpittle-Stained Trousers", popularity = "14.4%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "10.2%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "3.4%" },
            { id = 229306, name = "Breeches of Reclaiming Blight", popularity = "2.6%" }
        },
        FEET = {
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "42.6%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "16.7%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "10.3%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "5.1%" },
            { id = 237553, name = "Laboratory Test Slippers", popularity = "3.7%" }
        },
        FINGER1 = {
            { id = 178824, name = "BiSSignet of the False Accuser", popularity = "47.2%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "44.6%" },
            { id = 221200, name = "Radiant Necromancer's Band", popularity = "16.0%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "13.6%" },
            { id = 237570, name = "BiSLogic Gate: Omega", popularity = "13.3%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "53.5%" },
            { id = 237730, name = "Voidglass Spire", popularity = "7.6%" },
            { id = 185822, name = "Staff of Fractured Spacetime", popularity = "6.1%" },
            { id = 237728, name = "BiSVoidglass Kris", popularity = "6.0%" },
            { id = 222439, name = "Everforged Dagger", popularity = "5.3%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "16.5%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "2.0%" },
            { id = 237742, name = "Fractillus' Last Breath", popularity = "1.1%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "0.7%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "0.7%" }
        },
        TRINKET1 = {
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "43.6%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "42.1%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "22.5%" },
            { id = 242402, name = "BiSAraz's Ritual Forge", popularity = "17.6%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "13.5%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "58.8%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "35.2%" },
            { id = 212265, name = "Tempered Potion", popularity = "61.0%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "10.3%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "80.4%" }
        }
    },
    FERAL = {
        icon = "Interface/ICONS/Ability_Druid_CatForm",
        talent = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbzmZWYmZmZzmZsNzMzYmBAAAAAYJY2MwMjaGziZZmZWGzYGAAAAAAYAAAAAamlZZmZbAALgZAYhBD",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "60.6%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "76.6%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.6%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "68.5%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "52.6%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "58.7%" },
            MAINHAND = { id = 223765, name = "Stonebound Artistry", popularity = "50.3%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "66.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.1%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "66.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.1%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        HEAD = {
            { id = 237682, name = "BiSSkymane of the Mother Eagle", popularity = "83.4%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "3.0%" },
            { id = 229307, name = "Branches of Reclaiming Blight", popularity = "2.0%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.4%" },
            { id = 221163, name = "Whispering Mask", popularity = "1.4%" }
        },
        NECK = {
            { id = 178827, name = "Sin Stained Pendant", popularity = "24.4%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "22.4%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "10.5%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "8.4%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "6.2%" }
        },
        SHOULDERS = {
            { id = 237680, name = "BiSRitual Pauldrons of the Mother Eagle", popularity = "68.7%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "5.2%" },
            { id = 185802, name = "Breakbeat Shoulderguards", popularity = "4.8%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "3.9%" },
            { id = 237552, name = "Deathbound Shoulderpads", popularity = "3.6%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.4%" }
        },
        CHEST = {
            { id = 237685, name = "Vest of the Mother Eagle", popularity = "77.6%" },
            { id = 185786, name = "BiSSo'azmi's Fractal Vest", popularity = "4.9%" },
            { id = 246273, name = "Vest of Refracted Shadows", popularity = "3.5%" },
            { id = 219328, name = "Rune-Branded Tunic", popularity = "1.7%" },
            { id = 229310, name = "Robes of Reclaiming Blight", popularity = "1.6%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "62.8%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "8.0%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "6.7%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "5.8%" },
            { id = 237546, name = "Bindings of Lost Essence", popularity = "3.3%" }
        },
        HANDS = {
            { id = 237683, name = "BiSWings of the Mother Eagle", popularity = "79.9%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "3.2%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "2.5%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "2.4%" },
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "2.1%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "44.5%" },
            { id = 219331, name = "BiSRune-Branded Waistband", popularity = "33.6%" },
            { id = 237533, name = "Atomic Phasebelt", popularity = "5.3%" },
            { id = 221134, name = "Shadow Congregant's Belt", popularity = "3.8%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "2.7%" }
        },
        LEGS = {
            { id = 237681, name = "BiSBreeches of the Mother Eagle", popularity = "81.5%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "3.0%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "2.8%" },
            { id = 242473, name = "Spittle-Stained Trousers", popularity = "2.4%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.4%" }
        },
        FEET = {
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "43.9%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "12.7%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "10.5%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "6.1%" },
            { id = 211015, name = "Treasure-Seeker's Boots", popularity = "3.9%" }
        },
        FINGER1 = {
            { id = 178824, name = "Signet of the False Accuser", popularity = "37.9%" },
            { id = 221200, name = "BiSRadiant Necromancer's Band", popularity = "28.2%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "26.8%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "13.4%" },
            { id = 246281, name = "BiSRing of the Panoply", popularity = "13.0%" }
        },
        MAIN_HAND = {
            { id = 222448, name = "Charged Halberd", popularity = "34.9%" },
            { id = 237739, name = "Obliteration Beamglaive", popularity = "13.5%" },
            { id = 221159, name = "BiSHarvester's Interdiction", popularity = "12.5%" },
            { id = 222567, name = "Vagabond's Careful Crutch", popularity = "7.8%" },
            { id = 242481, name = "Spellstrike Warplance", popularity = "6.7%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "35.2%" },
            { id = 242402, name = "BiSAraz's Ritual Forge", popularity = "33.1%" },
            { id = 219308, name = "Signet of the Priory", popularity = "30.9%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "24.3%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "12.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "66.9%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "29.2%" },
            { id = 212265, name = "Tempered Potion", popularity = "63.9%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "10.9%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "77.7%" }
        }
    },
    GUARDIAN = {
        icon = "Interface/ICONS/Ability_Racial_BearForm",
        talent = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzYmhZWmZMjZMzYhZGmFLDYzwoJyMziZbmZWGzYAAAAAAwwYALbzshxsMAmAAAA2MmBgFjhB",
        statprio = "Haste > Vers > Mastery > Crit",
        enchants = {
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "61.0%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "50.6%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "78.6%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "60.7%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "54.7%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "46.0%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "44.6%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "34.5%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "26.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.5%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "34.5%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "26.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.5%" }
        },
        HEAD = {
            { id = 237682, name = "BiSSkymane of the Mother Eagle", popularity = "83.7%" },
            { id = 229307, name = "Branches of Reclaiming Blight", popularity = "2.9%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.8%" },
            { id = 221163, name = "Whispering Mask", popularity = "1.6%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "1.5%" }
        },
        NECK = {
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "43.2%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "11.7%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "8.7%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "7.3%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "6.9%" }
        },
        SHOULDERS = {
            { id = 237680, name = "BiSRitual Pauldrons of the Mother Eagle", popularity = "83.0%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "2.6%" },
            { id = 229305, name = "Jaws of Reclaiming Blight", popularity = "2.2%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "1.9%" },
            { id = 242486, name = "Mantle of Wounded Fate", popularity = "1.6%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.4%" }
        },
        CHEST = {
            { id = 237685, name = "BiSVest of the Mother Eagle", popularity = "81.7%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "4.0%" },
            { id = 229310, name = "Robes of Reclaiming Blight", popularity = "2.0%" },
            { id = 242482, name = "Reinforced Stalkerhide Vest", popularity = "1.6%" },
            { id = 185786, name = "So'azmi's Fractal Vest", popularity = "1.6%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "59.5%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "9.2%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "6.1%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "5.2%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "3.8%" }
        },
        HANDS = {
            { id = 237683, name = "Wings of the Mother Eagle", popularity = "59.8%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "14.2%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "4.4%" },
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "4.4%" },
            { id = 237975, name = "Void-Scarred Blade's Grips", popularity = "3.8%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "44.9%" },
            { id = 219502, name = "BiSAdrenal Surge Clasp", popularity = "19.0%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "15.9%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "4.2%" },
            { id = 185809, name = "Venza's Powderbelt", popularity = "3.6%" }
        },
        LEGS = {
            { id = 237681, name = "BiSBreeches of the Mother Eagle", popularity = "71.4%" },
            { id = 242473, name = "Spittle-Stained Trousers", popularity = "4.5%" },
            { id = 185801, name = "Anomalous Starlit Breeches", popularity = "3.2%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "3.0%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "2.8%" }
        },
        FEET = {
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "29.4%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "15.3%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "13.3%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "10.6%" },
            { id = 219327, name = "Rune-Branded Kickers", popularity = "7.0%" }
        },
        FINGER1 = {
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "46.0%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "21.4%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "20.9%" },
            { id = 221141, name = "High Nerubian Signet", popularity = "15.3%" },
            { id = 246281, name = "BiSRing of the Panoply", popularity = "13.9%" }
        },
        MAIN_HAND = {
            { id = 222448, name = "Charged Halberd", popularity = "28.7%" },
            { id = 221159, name = "BiSHarvester's Interdiction", popularity = "16.8%" },
            { id = 242481, name = "Spellstrike Warplance", popularity = "9.3%" },
            { id = 222567, name = "Vagabond's Careful Crutch", popularity = "8.1%" },
            { id = 185779, name = "Spire of Expurgation", popularity = "5.6%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "29.0%" },
            { id = 242401, name = "BiSBrand of Ceaseless Ire", popularity = "26.9%" },
            { id = 232543, name = "Ringing Ritual Mud", popularity = "22.4%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "17.4%" },
            { id = 219309, name = "BiSTome of Light's Devotion", popularity = "14.9%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "35.8%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "13.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "29.9%" },
            { id = 222720, name = "The Sushi Special", popularity = "28.9%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "65.1%" }
        }
    },
    RESTORATION = {
        icon = "Interface/ICONS/Spell_Nature_HealingTouch",
        talent = "CkGAAAAAAAAAAAAAAAAAAAAAAsxMzYxMzMzsY2GDGLLjtFbzAAAAAAAAAAAAYbQ2gJDzMjZxsMzYZGzMDAAAAAAAMAAAAAgZbmtmtZWsxYGYYWAN",
        statprio = "Haste > Mastery > Vers > Crit",
        enchants = {
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "47.0%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "56.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "74.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "65.0%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "37.4%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "56.3%" },
            MAINHAND = { id = 223762, name = "Stormrider's Fury", popularity = "42.1%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "34.2%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "20.0%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "11.7%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" }
        },
        gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "34.2%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "20.0%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "11.7%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" }
        },
        HEAD = {
            { id = 237682, name = "Skymane of the Mother Eagle", popularity = "87.2%" },
            { id = 229307, name = "Branches of Reclaiming Blight", popularity = "2.3%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "1.4%" },
            { id = 221163, name = "Whispering Mask", popularity = "1.3%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "0.8%" }
        },
        NECK = {
            { id = 178827, name = "Sin Stained Pendant", popularity = "29.2%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "28.8%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "8.1%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "6.3%" },
            { id = 237569, name = "Duskblaze's Desperation", popularity = "4.5%" }
        },
        SHOULDERS = {
            { id = 237680, name = "Ritual Pauldrons of the Mother Eagle", popularity = "85.5%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "2.4%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "1.8%" },
            { id = 229305, name = "Jaws of Reclaiming Blight", popularity = "1.7%" },
            { id = 242486, name = "Mantle of Wounded Fate", popularity = "1.2%" }
        },
        BACK = {
            { id = 235499, name = "Reshii Wraps", popularity = "96.6%" }
        },
        CHEST = {
            { id = 237685, name = "Vest of the Mother Eagle", popularity = "87.1%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "1.6%" },
            { id = 229310, name = "Robes of Reclaiming Blight", popularity = "1.6%" },
            { id = 185786, name = "So'azmi's Fractal Vest", popularity = "1.5%" },
            { id = 242482, name = "Reinforced Stalkerhide Vest", popularity = "1.1%" }
        },
        WRISTS = {
            { id = 219334, name = "Rune-Branded Armbands", popularity = "45.9%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "21.1%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "5.4%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "5.4%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "4.2%" }
        },
        HANDS = {
            { id = 237683, name = "Wings of the Mother Eagle", popularity = "75.0%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "6.3%" },
            { id = 229308, name = "Grips of Reclaiming Blight", popularity = "3.4%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "3.2%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "1.8%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "54.1%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "16.1%" },
            { id = 178823, name = "Waistcord of Dark Devotion", popularity = "5.6%" },
            { id = 237679, name = "Dreamsash of the Mother Eagle", popularity = "4.6%" },
            { id = 237533, name = "Atomic Phasebelt", popularity = "3.5%" }
        },
        LEGS = {
            { id = 237681, name = "Breeches of the Mother Eagle", popularity = "47.0%" },
            { id = 242473, name = "Spittle-Stained Trousers", popularity = "16.1%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "11.4%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "8.2%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "2.8%" }
        },
        FEET = {
            { id = 243306, name = "Interloper's Reinforced Sandals", popularity = "37.3%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "19.5%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "9.9%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "7.7%" },
            { id = 237553, name = "Laboratory Test Slippers", popularity = "4.8%" }
        },
        FINGER1 = {
            { id = 242491, name = "Whispers of K'aresh", popularity = "39.3%" },
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "35.9%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "27.8%" },
            { id = 215133, name = "Binding of Binding", popularity = "13.3%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "12.9%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "52.5%" },
            { id = 237730, name = "Voidglass Spire", popularity = "12.9%" },
            { id = 185822, name = "Staff of Fractured Spacetime", popularity = "7.5%" },
            { id = 237728, name = "Voidglass Kris", popularity = "4.1%" },
            { id = 222439, name = "Everforged Dagger", popularity = "3.6%" }
        },
        OFF_HAND = {
            { id = 222566, name = "Vagabond's Torch", popularity = "8.7%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "2.4%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "1.2%" },
            { id = 237742, name = "Fractillus' Last Breath", popularity = "1.1%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "0.9%" }
        },
        TRINKET1 = {
            { id = 190958, name = "So'leah's Secret Technique", popularity = "46.1%" },
            { id = 242393, name = "Loom'ithar's Living Silk", popularity = "39.2%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "19.0%" },
            { id = 219312, name = "Empowering Crystal of Anub'ikkaj", popularity = "15.8%" },
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "12.5%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "39.2%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "18.5%" },
            { id = 212241, name = "Algari Mana Potion", popularity = "13.4%" },
            { id = 222720, name = "The Sushi Special", popularity = "25.6%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "67.7%" }
        }
    }
}
