-- Auto-generated by scraper
WishListData_Mage = {
    ARCANE = {
        icon = "Interface/ICONS/Spell_Holy_MagicalSentry",
        talent = "C4DAAAAAAAAAAAAAAAAAAAAAAMjhZbGMDzMLwYmhx0MjZAAAAAAYAAzMTLz22MAA2AAAAAAYDAjBzsMLzYmxYGmZmZGzYWGD",
        statprio = "Haste > Vers > Mastery > Crit",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "12.1%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "55.2%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "72.1%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "67.7%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "87.4%" },
            RINGS = { id = 223680, name = "Radiant Versatility", popularity = "47.6%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "65.0%" },
            MAINHAND = { id = 223768, name = "Oathsworn's Tenacity", popularity = "38.0%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "70.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "4.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "1.8%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213485, name = "Versatile Emerald", popularity = "55.2%" },
            { id = 213470, name = "Quick Sapphire", popularity = "46.6%" },
            { id = 213461, name = "Versatile Ruby", popularity = "30.6%" }
        },
        HEAD = {
            { id = 237718, name = "BiSAugur's Ephemeral Wide-Brim", popularity = "61.5%" },
            { id = 229343, name = "Aspectral Emissary's Crystalline Cowl", popularity = "14.9%" },
            { id = 242477, name = "Wasteland Devotee's Wrappings", popularity = "5.4%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "4.7%" },
            { id = 185795, name = "Cowl of Branching Fate", popularity = "2.8%" }
        },
        NECK = {
            { id = 252009, name = "Bloodstained Memento", popularity = "22.7%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "16.1%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "13.2%" },
            { id = 237568, name = "BiSChrysalis of Sundered Souls", popularity = "11.3%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "8.3%" }
        },
        SHOULDERS = {
            { id = 237716, name = "BiSAugur's Ephemeral Orbs of Power", popularity = "60.0%" },
            { id = 229341, name = "Aspectral Emissary's Arcane Vents", popularity = "17.7%" },
            { id = 221135, name = "Fanatic's Blackened Shoulderwraps", popularity = "4.1%" },
            { id = 246276, name = "Sinlight Shoulderpads", popularity = "3.2%" },
            { id = 237547, name = "Mounted Manacannons", popularity = "2.6%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.8%" }
        },
        CHEST = {
            { id = 237721, name = "BiSAugur's Ephemeral Habiliments", popularity = "65.2%" },
            { id = 229346, name = "Aspectral Emissary's Primal Robes", popularity = "15.7%" },
            { id = 221126, name = "Zealous Warden's Raiment", popularity = "3.8%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "3.7%" },
            { id = 185782, name = "Robes of Midnight Bargains", popularity = "2.1%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "45.3%" },
            { id = 246279, name = "Fizzlefuse Cuffs", popularity = "13.2%" },
            { id = 242468, name = "Al'dani Attendant's Gauze", popularity = "11.4%" },
            { id = 185814, name = "Auctioneer's Counting Bracers", popularity = "6.5%" },
            { id = 237534, name = "Singed Sievecuffs", popularity = "4.5%" }
        },
        HANDS = {
            { id = 237719, name = "Augur's Ephemeral Mitts", popularity = "53.2%" },
            { id = 229344, name = "Aspectral Emissary's Hardened Grasp", popularity = "13.8%" },
            { id = 242490, name = "Ancient Oracle's Caress", popularity = "6.1%" },
            { id = 246275, name = "BiSCodebreaker's Cunning Handwraps", popularity = "4.5%" },
            { id = 178833, name = "Stonefiend Shaper's Mitts", popularity = "4.4%" }
        },
        WAIST = {
            { id = 242664, name = "BiSDurable Information Securing Container", popularity = "86.6%" },
            { id = 222816, name = "Consecrated Cord", popularity = "2.9%" },
            { id = 221158, name = "Burrower's Cinch", popularity = "1.8%" },
            { id = 178822, name = "Cord of the Dark Word", popularity = "1.5%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "1.4%" }
        },
        LEGS = {
            { id = 237717, name = "BiSAugur's Ephemeral Trousers", popularity = "63.2%" },
            { id = 229342, name = "Aspectral Emissary's Trousers", popularity = "16.9%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "4.4%" },
            { id = 221164, name = "Archaic Venomancer's Legwraps", popularity = "4.1%" },
            { id = 185799, name = "Hyperlight Leggings", popularity = "2.3%" }
        },
        FEET = {
            { id = 243305, name = "BiSInterloper's Silken Striders", popularity = "27.8%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "22.1%" },
            { id = 221149, name = "Membranous Slippers", popularity = "10.6%" },
            { id = 178831, name = "Slippers of Leavened Station", popularity = "9.1%" },
            { id = 222814, name = "Consecrated Slippers", popularity = "6.4%" }
        },
        FINGER1 = {
            { id = 221141, name = "BiSHigh Nerubian Signet", popularity = "26.2%" },
            { id = 221200, name = "Radiant Necromancer's Band", popularity = "24.3%" },
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "22.8%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "20.2%" },
            { id = 231265, name = "The Jastor Diamond", popularity = "15.1%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "26.9%" },
            { id = 242484, name = "Soul-Scribe's Tabiqa Dagger", popularity = "7.4%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "6.6%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "6.0%" },
            { id = 237728, name = "Voidglass Kris", popularity = "5.6%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "38.5%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "4.2%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "3.0%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "2.8%" },
            { id = 237724, name = "Iris of the Dark Beyond", popularity = "1.4%" }
        },
        TRINKET1 = {
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "45.4%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "28.1%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "17.7%" },
            { id = 230192, name = "Mug's Moxie Jug", popularity = "16.4%" },
            { id = 219308, name = "Signet of the Priory", popularity = "14.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "62.1%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "39.0%" },
            { id = 212265, name = "Tempered Potion", popularity = "71.2%" },
            { id = 222720, name = "The Sushi Special", popularity = "30.3%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "84.6%" }
        }
    },
    FIRE = {
        icon = "Interface/ICONS/Spell_Fire_FireBolt",
        talent = "C8DAAAAAAAAAAAAAAAAAAAAAAYGMbGMzYmZxDAzMjpxMjZGAAAAAADAYmZaZW2mBAYzMzgxMDzYWMLjhZmNzsNjtZWwAAAAAAAA",
        statprio = "Haste > Mastery > Vers > Crit",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "10.6%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "70.6%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "66.1%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "65.5%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "89.0%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "70.3%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.5%" },
            MAINHAND = { id = 223762, name = "Stormrider's Fury", popularity = "28.6%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "72.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "3.6%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213485, name = "Versatile Emerald", popularity = "60.4%" },
            { id = 213470, name = "Quick Sapphire", popularity = "49.1%" },
            { id = 213482, name = "Masterful Emerald", popularity = "45.5%" },
            { id = 213494, name = "Quick Onyx", popularity = "38.8%" }
        },
        HEAD = {
            { id = 237718, name = "Augur's Ephemeral Wide-Brim", popularity = "50.2%" },
            { id = 229343, name = "Aspectral Emissary's Crystalline Cowl", popularity = "15.6%" },
            { id = 242477, name = "Wasteland Devotee's Wrappings", popularity = "11.5%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "5.1%" },
            { id = 222818, name = "Consecrated Hood", popularity = "3.9%" }
        },
        NECK = {
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "28.7%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "24.1%" },
            { id = 237569, name = "BiSDuskblaze's Desperation", popularity = "7.8%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "6.6%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "5.5%" }
        },
        SHOULDERS = {
            { id = 237716, name = "BiSAugur's Ephemeral Orbs of Power", popularity = "68.4%" },
            { id = 229341, name = "Aspectral Emissary's Arcane Vents", popularity = "14.3%" },
            { id = 237547, name = "Mounted Manacannons", popularity = "3.7%" },
            { id = 246276, name = "Sinlight Shoulderpads", popularity = "2.9%" },
            { id = 221135, name = "Fanatic's Blackened Shoulderwraps", popularity = "2.1%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "97.0%" }
        },
        CHEST = {
            { id = 237721, name = "BiSAugur's Ephemeral Habiliments", popularity = "71.7%" },
            { id = 229346, name = "Aspectral Emissary's Primal Robes", popularity = "13.9%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "3.2%" },
            { id = 237527, name = "Frock of Spirit's Reunion", popularity = "1.7%" },
            { id = 185782, name = "Robes of Midnight Bargains", popularity = "1.4%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "44.4%" },
            { id = 246279, name = "Fizzlefuse Cuffs", popularity = "18.5%" },
            { id = 237558, name = "Conjoined Glass Bracers", popularity = "8.2%" },
            { id = 185814, name = "Auctioneer's Counting Bracers", popularity = "6.3%" },
            { id = 242468, name = "Al'dani Attendant's Gauze", popularity = "5.3%" }
        },
        HANDS = {
            { id = 237719, name = "BiSAugur's Ephemeral Mitts", popularity = "66.9%" },
            { id = 242490, name = "Ancient Oracle's Caress", popularity = "6.2%" },
            { id = 229344, name = "Aspectral Emissary's Hardened Grasp", popularity = "5.5%" },
            { id = 185793, name = "Cyphered Gloves", popularity = "3.9%" },
            { id = 178833, name = "Stonefiend Shaper's Mitts", popularity = "3.0%" }
        },
        WAIST = {
            { id = 242664, name = "Durable Information Securing Container", popularity = "83.6%" },
            { id = 222816, name = "Consecrated Cord", popularity = "4.0%" },
            { id = 237538, name = "BiSForgeweaver's Journal Holster", popularity = "3.9%" },
            { id = 221158, name = "Burrower's Cinch", popularity = "1.8%" },
            { id = 178822, name = "Cord of the Dark Word", popularity = "0.9%" }
        },
        LEGS = {
            { id = 237717, name = "BiSAugur's Ephemeral Trousers", popularity = "68.5%" },
            { id = 229342, name = "Aspectral Emissary's Trousers", popularity = "13.5%" },
            { id = 221164, name = "Archaic Venomancer's Legwraps", popularity = "4.5%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "2.5%" },
            { id = 237542, name = "Stellar Navigation Slacks", popularity = "2.3%" }
        },
        FEET = {
            { id = 243305, name = "BiSInterloper's Silken Striders", popularity = "34.0%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "21.8%" },
            { id = 178831, name = "Slippers of Leavened Station", popularity = "9.2%" },
            { id = 221149, name = "Membranous Slippers", popularity = "5.1%" },
            { id = 222814, name = "Consecrated Slippers", popularity = "4.9%" }
        },
        FINGER1 = {
            { id = 242491, name = "Whispers of K'aresh", popularity = "40.1%" },
            { id = 185813, name = "BiSSignet of Collapsing Stars", popularity = "28.8%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "14.5%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "12.9%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "12.1%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "27.3%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "10.2%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "8.4%" },
            { id = 237728, name = "Voidglass Kris", popularity = "6.2%" },
            { id = 222444, name = "Charged Hexsword", popularity = "5.9%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "41.7%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "3.2%" },
            { id = 237724, name = "Iris of the Dark Beyond", popularity = "2.0%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "1.7%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "1.0%" }
        },
        TRINKET1 = {
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "48.0%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "36.9%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "19.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "10.6%" },
            { id = 190958, name = "So'leah's Secret Technique", popularity = "10.1%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "54.6%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "38.0%" },
            { id = 212265, name = "Tempered Potion", popularity = "67.9%" },
            { id = 222720, name = "The Sushi Special", popularity = "36.0%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "84.1%" }
        }
    },
    FROST = {
        icon = "Interface/ICONS/Spell_Frost_FrostBolt02",
        talent = "CAEAAAAAAAAAAAAAAAAAAAAAAMzYzsZwMMzsAjZGNGzDMmZmhhZwDMzMzMzMzMzMmZmxMzyMNzsMLAAAwCAAAAAAmNAAAAAAAA",
        statprio = "Haste > Vers > Crit > Mastery",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "12.3%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "72.3%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "62.9%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "64.4%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "86.0%" },
            RINGS = { id = 223680, name = "Radiant Versatility", popularity = "37.8%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "57.1%" },
            MAINHAND = { id = 223768, name = "Oathsworn's Tenacity", popularity = "38.0%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "64.8%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "5.7%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213485, name = "Versatile Emerald", popularity = "41.4%" },
            { id = 213470, name = "Quick Sapphire", popularity = "40.7%" },
            { id = 213461, name = "Versatile Ruby", popularity = "38.0%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "35.2%" }
        },
        HEAD = {
            { id = 237718, name = "BiSAugur's Ephemeral Wide-Brim", popularity = "56.7%" },
            { id = 229343, name = "Aspectral Emissary's Crystalline Cowl", popularity = "15.0%" },
            { id = 242477, name = "Wasteland Devotee's Wrappings", popularity = "6.7%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "3.6%" },
            { id = 185795, name = "Cowl of Branching Fate", popularity = "3.4%" }
        },
        NECK = {
            { id = 252009, name = "Bloodstained Memento", popularity = "26.0%" },
            { id = 185842, name = "BiSOrnately Engraved Amplifier", popularity = "10.9%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "10.7%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "10.1%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "6.5%" }
        },
        SHOULDERS = {
            { id = 237716, name = "BiSAugur's Ephemeral Orbs of Power", popularity = "54.9%" },
            { id = 229341, name = "Aspectral Emissary's Arcane Vents", popularity = "20.9%" },
            { id = 221135, name = "Fanatic's Blackened Shoulderwraps", popularity = "4.7%" },
            { id = 185804, name = "Harmonious Spaulders", popularity = "2.6%" },
            { id = 246276, name = "Sinlight Shoulderpads", popularity = "2.5%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.4%" }
        },
        CHEST = {
            { id = 237721, name = "Augur's Ephemeral Habiliments", popularity = "51.2%" },
            { id = 229346, name = "Aspectral Emissary's Primal Robes", popularity = "20.8%" },
            { id = 221126, name = "BiSZealous Warden's Raiment", popularity = "7.7%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "6.3%" },
            { id = 185782, name = "Robes of Midnight Bargains", popularity = "2.2%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "40.4%" },
            { id = 242468, name = "Al'dani Attendant's Gauze", popularity = "13.7%" },
            { id = 246279, name = "Fizzlefuse Cuffs", popularity = "10.6%" },
            { id = 185814, name = "Auctioneer's Counting Bracers", popularity = "7.1%" },
            { id = 237534, name = "Singed Sievecuffs", popularity = "5.4%" }
        },
        HANDS = {
            { id = 237719, name = "BiSAugur's Ephemeral Mitts", popularity = "55.0%" },
            { id = 229344, name = "Aspectral Emissary's Hardened Grasp", popularity = "19.3%" },
            { id = 178833, name = "Stonefiend Shaper's Mitts", popularity = "5.5%" },
            { id = 242490, name = "Ancient Oracle's Caress", popularity = "3.4%" },
            { id = 246275, name = "Codebreaker's Cunning Handwraps", popularity = "2.1%" }
        },
        WAIST = {
            { id = 242664, name = "Durable Information Securing Container", popularity = "75.3%" },
            { id = 221158, name = "Burrower's Cinch", popularity = "4.9%" },
            { id = 222816, name = "Consecrated Cord", popularity = "4.3%" },
            { id = 178822, name = "BiSCord of the Dark Word", popularity = "3.9%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "2.1%" }
        },
        LEGS = {
            { id = 237717, name = "BiSAugur's Ephemeral Trousers", popularity = "50.3%" },
            { id = 229342, name = "Aspectral Emissary's Trousers", popularity = "22.4%" },
            { id = 221164, name = "Archaic Venomancer's Legwraps", popularity = "7.4%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "5.5%" },
            { id = 185799, name = "Hyperlight Leggings", popularity = "2.7%" }
        },
        FEET = {
            { id = 243305, name = "BiSInterloper's Silken Striders", popularity = "21.7%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "21.0%" },
            { id = 178831, name = "Slippers of Leavened Station", popularity = "10.8%" },
            { id = 221149, name = "Membranous Slippers", popularity = "10.6%" },
            { id = 222814, name = "Consecrated Slippers", popularity = "7.0%" }
        },
        FINGER1 = {
            { id = 185813, name = "BiSSignet of Collapsing Stars", popularity = "22.1%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "21.2%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "20.8%" },
            { id = 221141, name = "BiSHigh Nerubian Signet", popularity = "16.9%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "13.2%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "26.3%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "7.1%" },
            { id = 178829, name = "Nathrian Ferula", popularity = "6.0%" },
            { id = 237735, name = "Voidglass Sovereign's Blade", popularity = "5.9%" },
            { id = 237728, name = "BiSVoidglass Kris", popularity = "5.8%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "31.1%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "5.5%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "3.7%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "2.8%" },
            { id = 237724, name = "Iris of the Dark Beyond", popularity = "1.9%" }
        },
        TRINKET1 = {
            { id = 242497, name = "BiSAzhiccaran Parapodia", popularity = "35.2%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "21.7%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "17.5%" },
            { id = 219312, name = "Empowering Crystal of Anub'ikkaj", popularity = "17.1%" },
            { id = 230192, name = "Mug's Moxie Jug", popularity = "12.0%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "48.4%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "30.3%" },
            { id = 212265, name = "Tempered Potion", popularity = "61.3%" },
            { id = 222720, name = "The Sushi Special", popularity = "26.8%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "79.1%" }
        }
    }
}
