-- Auto-generated by scraper
WishListData_Shaman = {
    ELEMENTAL = {
        icon = "Interface/ICONS/Spell_Nature_Lightning",
        talent = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAYb2WmZmZGz2sMGMMDDAAAAAYzMG2gFYGGasBAmtpZwYjxMNMzMjZsMjZsYWGLWMzMzYYmtBA",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "65.1%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "79.0%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "55.7%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "64.9%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "88.3%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "53.9%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "58.2%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "35.3%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "66.7%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "13.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.8%" }
        },
        gems = {
            { id = 213494, name = "Quick Onyx", popularity = "63.5%" },
            { id = 213482, name = "Masterful Emerald", popularity = "58.6%" },
            { id = 213458, name = "Masterful Ruby", popularity = "29.3%" },
            { id = 213470, name = "Quick Sapphire", popularity = "22.7%" }
        },
        HEAD = {
            { id = 229262, name = "Gale Sovereign's Charged Hood", popularity = "77.4%" },
            { id = 237637, name = "Aspect of Channeled Fury", popularity = "7.5%" },
            { id = 221156, name = "Cryptbound Headpiece", popularity = "4.5%" },
            { id = 178816, name = "BiSNathrian Usurper's Mask", popularity = "3.5%" },
            { id = 185796, name = "Dragonbane Diadem", popularity = "0.9%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "29.7%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "17.9%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "12.8%" },
            { id = 251880, name = "BiSMomma's Mega Medallion", popularity = "10.1%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "9.2%" }
        },
        SHOULDERS = {
            { id = 229260, name = "Gale Sovereign's Zephyrs", popularity = "73.6%" },
            { id = 237635, name = "BiSFangs of Channeled Fury", popularity = "14.4%" },
            { id = 242472, name = "Consumed Wastelander's Epaulets", popularity = "2.7%" },
            { id = 234503, name = "Skystreak's Hidden Missiles", popularity = "1.9%" },
            { id = 178821, name = "Mantle of Ephemeral Visages", popularity = "1.4%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "97.6%" },
            { id = 222817, name = "Consecrated Cloak", popularity = "0.1%" }
        },
        CHEST = {
            { id = 229265, name = "Gale Sovereign's Clouded Hauberk", popularity = "67.2%" },
            { id = 237640, name = "BiSFurs of Channeled Fury", popularity = "14.0%" },
            { id = 234502, name = "Bront's Singed Blastcoat", popularity = "5.2%" },
            { id = 221147, name = "Goliath's Chitinous Chainmail", popularity = "2.7%" },
            { id = 178815, name = "Soaring Decimator's Hauberk", popularity = "1.8%" }
        },
        WRISTS = {
            { id = 219342, name = "BiSGlyph-Etched Vambraces", popularity = "58.2%" },
            { id = 221124, name = "Consecrated Baron's Bindings", popularity = "12.4%" },
            { id = 228846, name = "Galvanic Graffiti Cuffs", popularity = "4.7%" },
            { id = 185816, name = "Confiscated Bracers of Concealment", popularity = "3.1%" },
            { id = 228878, name = "Made Manacles", popularity = "3.0%" }
        },
        HANDS = {
            { id = 229263, name = "Gale Sovereign's Grasps", popularity = "68.5%" },
            { id = 237638, name = "BiSClaws of Channeled Fury", popularity = "13.6%" },
            { id = 221119, name = "Holybound Grips", popularity = "2.8%" },
            { id = 221162, name = "Claws of Tainted Ichor", popularity = "2.7%" },
            { id = 168971, name = "Swift Pneumatic Grips", popularity = "2.1%" }
        },
        WAIST = {
            { id = 245965, name = "Durable Information Securing Container", popularity = "95.9%" },
            { id = 234501, name = "Portable Power Generator", popularity = "0.4%" },
            { id = 159361, name = "Shalebiter Interlinked Chain", popularity = "0.3%" },
            { id = 237554, name = "BiSClasp of Furious Freedom", popularity = "0.2%" },
            { id = 219339, name = "Glyph-Etched Binding", popularity = "0.2%" }
        },
        LEGS = {
            { id = 229261, name = "Gale Sovereign's Pantaloons", popularity = "40.0%" },
            { id = 237636, name = "BiSTassets of Channeled Fury", popularity = "16.7%" },
            { id = 246277, name = "Swampface's Oozewalkers", popularity = "11.2%" },
            { id = 219340, name = "Glyph-Etched Cuisses", popularity = "9.7%" },
            { id = 158341, name = "Chemical Blaster's Legguards", popularity = "6.9%" }
        },
        FEET = {
            { id = 219335, name = "Glyph-Etched Stompers", popularity = "21.1%" },
            { id = 221152, name = "Silksteel Striders", popularity = "12.7%" },
            { id = 242483, name = "Greaves of the Wild Pair", popularity = "10.4%" },
            { id = 178830, name = "Shardskin Sabatons", popularity = "7.0%" },
            { id = 243308, name = "BiSInterloper's Chain Boots", popularity = "5.9%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "71.4%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "22.6%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "15.3%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "13.9%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "12.5%" }
        },
        MAIN_HAND = {
            { id = 222445, name = "Charged Runeaxe", popularity = "12.9%" },
            { id = 222439, name = "Everforged Dagger", popularity = "8.8%" },
            { id = 178829, name = "Nathrian Ferula", popularity = "7.5%" },
            { id = 228901, name = "Big Earner's Bludgeon", popularity = "6.4%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "6.3%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "12.6%" },
            { id = 228889, name = "Titan of Industry", popularity = "9.3%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "5.7%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "5.7%" },
            { id = 222566, name = "BiSVagabond's Torch", popularity = "4.6%" }
        },
        TRINKET1 = {
            { id = 230192, name = "Mug's Moxie Jug", popularity = "47.7%" },
            { id = 230027, name = "House of Cards", popularity = "32.9%" },
            { id = 219308, name = "Signet of the Priory", popularity = "23.9%" },
            { id = 242497, name = "BiSAzhiccaran Parapodia", popularity = "14.8%" },
            { id = 242494, name = "BiSLily of the Eternal Weave", popularity = "14.7%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "79.3%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "34.4%" },
            { id = 212265, name = "Tempered Potion", popularity = "68.1%" },
            { id = 222733, name = "Feast of the Midnight Masquerade", popularity = "12.7%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "78.0%" }
        }
    },
    ENHANCEMENT = {
        icon = "Interface/ICONS/Spell_Shaman_ImprovedStormstrike",
        talent = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMDMzDMDzMz8AzMLzMYZAAAAAAAAAA2AsZGDbwCMDDNYBAzykZwswYmhZGzsNjlZMNLsMWYmBAYMA",
        statprio = "Mastery > Haste > Crit > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "70.4%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "84.1%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "59.9%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "68.9%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "90.3%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "66.2%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "67.7%" },
            MAINHAND = { id = 223765, name = "Stonebound Artistry", popularity = "47.2%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "73.2%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.7%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        gems = {
            { id = 213482, name = "Masterful Emerald", popularity = "73.1%" },
            { id = 213494, name = "Quick Onyx", popularity = "63.1%" },
            { id = 213455, name = "Quick Ruby", popularity = "28.1%" },
            { id = 213470, name = "Quick Sapphire", popularity = "26.5%" }
        },
        HEAD = {
            { id = 229262, name = "Gale Sovereign's Charged Hood", popularity = "79.3%" },
            { id = 237637, name = "BiSAspect of Channeled Fury", popularity = "12.0%" },
            { id = 221156, name = "Cryptbound Headpiece", popularity = "2.6%" },
            { id = 178816, name = "Nathrian Usurper's Mask", popularity = "1.1%" },
            { id = 185796, name = "Dragonbane Diadem", popularity = "0.4%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "32.8%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "24.1%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "13.9%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "8.8%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "4.7%" }
        },
        SHOULDERS = {
            { id = 229260, name = "Gale Sovereign's Zephyrs", popularity = "76.6%" },
            { id = 237635, name = "BiSFangs of Channeled Fury", popularity = "15.3%" },
            { id = 242472, name = "Consumed Wastelander's Epaulets", popularity = "1.8%" },
            { id = 178821, name = "Mantle of Ephemeral Visages", popularity = "1.0%" },
            { id = 185805, name = "Hylbrande's Retrofitted Shoulderguards", popularity = "0.6%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.9%" },
            { id = 229257, name = "Gale Sovereign's Breeze", popularity = "0.2%" }
        },
        CHEST = {
            { id = 229265, name = "Gale Sovereign's Clouded Hauberk", popularity = "69.8%" },
            { id = 237640, name = "Furs of Channeled Fury", popularity = "12.9%" },
            { id = 221147, name = "Goliath's Chitinous Chainmail", popularity = "3.7%" },
            { id = 234502, name = "Bront's Singed Blastcoat", popularity = "3.3%" },
            { id = 237529, name = "BiSHarvested Attendant's Uniform", popularity = "2.3%" }
        },
        WRISTS = {
            { id = 219342, name = "BiSGlyph-Etched Vambraces", popularity = "60.8%" },
            { id = 221124, name = "Consecrated Baron's Bindings", popularity = "13.9%" },
            { id = 228878, name = "Made Manacles", popularity = "4.9%" },
            { id = 228846, name = "Galvanic Graffiti Cuffs", popularity = "3.8%" },
            { id = 229258, name = "Gale Sovereign's Bracers", popularity = "2.5%" }
        },
        HANDS = {
            { id = 229263, name = "Gale Sovereign's Grasps", popularity = "68.5%" },
            { id = 237638, name = "BiSClaws of Channeled Fury", popularity = "14.5%" },
            { id = 228867, name = "Gravi-Gunk Handlers", popularity = "4.6%" },
            { id = 221162, name = "Claws of Tainted Ichor", popularity = "2.2%" },
            { id = 221119, name = "Holybound Grips", popularity = "1.7%" }
        },
        WAIST = {
            { id = 245965, name = "Durable Information Securing Container", popularity = "95.4%" },
            { id = 234501, name = "Portable Power Generator", popularity = "0.5%" },
            { id = 219339, name = "Glyph-Etched Binding", popularity = "0.4%" },
            { id = 168983, name = "Maniacal Monarch's Girdle", popularity = "0.3%" },
            { id = 159361, name = "Shalebiter Interlinked Chain", popularity = "0.2%" }
        },
        LEGS = {
            { id = 229261, name = "Gale Sovereign's Pantaloons", popularity = "32.5%" },
            { id = 237636, name = "BiSTassets of Channeled Fury", popularity = "21.6%" },
            { id = 158341, name = "Chemical Blaster's Legguards", popularity = "10.6%" },
            { id = 219340, name = "Glyph-Etched Cuisses", popularity = "10.0%" },
            { id = 246277, name = "Swampface's Oozewalkers", popularity = "9.9%" }
        },
        FEET = {
            { id = 219335, name = "Glyph-Etched Stompers", popularity = "18.1%" },
            { id = 221152, name = "Silksteel Striders", popularity = "12.2%" },
            { id = 221035, name = "Treads of the Galvanic Skysoarer", popularity = "9.7%" },
            { id = 221106, name = "Gloomstomper's Sabatons", popularity = "9.5%" },
            { id = 242483, name = "Greaves of the Wild Pair", popularity = "8.1%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "74.3%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "21.2%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "19.9%" },
            { id = 242491, name = "BiSWhispers of K'aresh", popularity = "17.7%" },
            { id = 159462, name = "Footbomb Championship Ring", popularity = "15.5%" }
        },
        MAIN_HAND = {
            { id = 222451, name = "Charged Slicer", popularity = "22.2%" },
            { id = 222446, name = "BiSCharged Facesmasher", popularity = "21.6%" },
            { id = 228899, name = "Gallywix's Iron Thumb", popularity = "7.8%" },
            { id = 222442, name = "Everforged Mace", popularity = "6.2%" },
            { id = 221128, name = "Starforged Seraph's Mace", popularity = "5.2%" }
        },
        OFF_HAND = {
            { id = 222451, name = "Charged Slicer", popularity = "19.1%" },
            { id = 222446, name = "BiSCharged Facesmasher", popularity = "19.0%" },
            { id = 228899, name = "Gallywix's Iron Thumb", popularity = "10.5%" },
            { id = 222442, name = "Everforged Mace", popularity = "7.6%" },
            { id = 237738, name = "BiSUnbound Training Claws", popularity = "5.6%" }
        },
        TRINKET1 = {
            { id = 232541, name = "BiSImprovised Seaforium Pacemaker", popularity = "72.8%" },
            { id = 219308, name = "BiSSignet of the Priory", popularity = "44.8%" },
            { id = 230027, name = "House of Cards", popularity = "21.2%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "12.5%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "10.8%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "70.4%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "32.7%" },
            { id = 212265, name = "Tempered Potion", popularity = "71.5%" },
            { id = 222720, name = "The Sushi Special", popularity = "12.8%" },
            { id = nil, name = "Flametongue Weapon", popularity = "97.1%" },
            { id = nil, name = "Windfury Weapon", popularity = "97.1%" }
        }
    },
    RESTORATION = {
        icon = "Interface/ICONS/Spell_Nature_MagicImmunity",
        talent = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmZmZbmthZegZzsNWMjFLmZBGwAmFmAjFMzsYZmtZmhMbLMz0YmhhxixM2MLjlZhBAAD",
        statprio = "Crit > Vers > Haste > Mastery",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "47.9%" },
            LEGS = { id = 222896, name = "Daybreak Spellthread", popularity = "60.3%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "32.0%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "64.5%" },
            CHEST = { id = 223686, name = "Council's Intellect", popularity = "48.7%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "65.2%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "48.6%" },
            MAINHAND = { id = 223778, name = "Authority of Fiery Resolve", popularity = "67.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "35.6%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "21.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "20.0%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" }
        },
        gems = {
            { id = 213461, name = "Versatile Ruby", popularity = "78.5%" },
            { id = 213467, name = "Deadly Sapphire", popularity = "50.9%" },
            { id = 213479, name = "Deadly Emerald", popularity = "38.7%" },
            { id = 213491, name = "Deadly Onyx", popularity = "26.5%" }
        },
        HEAD = {
            { id = 229262, name = "Gale Sovereign's Charged Hood", popularity = "39.4%" },
            { id = 237637, name = "BiSAspect of Channeled Fury", popularity = "13.9%" },
            { id = 228859, name = "Sanitized Scraphood", popularity = "8.9%" },
            { id = 219337, name = "Glyph-Etched Guise", popularity = "7.3%" },
            { id = 235223, name = "Psychogenic Prognosticator's Lenses", popularity = "6.7%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "32.7%" },
            { id = 221103, name = "Flickering Glowtorc", popularity = "23.8%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "11.1%" },
            { id = 185842, name = "BiSOrnately Engraved Amplifier", popularity = "3.7%" },
            { id = 215134, name = "Fractured Gemstone Locket", popularity = "3.6%" }
        },
        SHOULDERS = {
            { id = 229260, name = "Gale Sovereign's Zephyrs", popularity = "68.8%" },
            { id = 237635, name = "Fangs of Channeled Fury", popularity = "10.2%" },
            { id = 234503, name = "Skystreak's Hidden Missiles", popularity = "3.2%" },
            { id = 242472, name = "Consumed Wastelander's Epaulets", popularity = "2.3%" },
            { id = 178821, name = "Mantle of Ephemeral Visages", popularity = "2.1%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.6%" },
            { id = 221109, name = "Candlebearer's Shroud", popularity = "0.2%" },
            { id = 222817, name = "Consecrated Cloak", popularity = "0.2%" },
            { id = 228839, name = "Undercircuit Racing Flag", popularity = "0.1%" }
        },
        CHEST = {
            { id = 229265, name = "Gale Sovereign's Clouded Hauberk", popularity = "71.6%" },
            { id = 237640, name = "BiSFurs of Channeled Fury", popularity = "13.1%" },
            { id = 221147, name = "Goliath's Chitinous Chainmail", popularity = "2.6%" },
            { id = 178815, name = "Soaring Decimator's Hauberk", popularity = "2.4%" },
            { id = 234502, name = "Bront's Singed Blastcoat", popularity = "1.9%" }
        },
        WRISTS = {
            { id = 219342, name = "BiSGlyph-Etched Vambraces", popularity = "44.1%" },
            { id = 221059, name = "I'pa's Pale Aleguards", popularity = "10.1%" },
            { id = 229258, name = "Gale Sovereign's Bracers", popularity = "9.9%" },
            { id = 158357, name = "Bindings of Enraged Earth", popularity = "9.0%" },
            { id = 221124, name = "Consecrated Baron's Bindings", popularity = "5.5%" }
        },
        HANDS = {
            { id = 229263, name = "Gale Sovereign's Grasps", popularity = "71.0%" },
            { id = 237638, name = "BiSClaws of Channeled Fury", popularity = "10.9%" },
            { id = 221162, name = "Claws of Tainted Ichor", popularity = "4.4%" },
            { id = 221119, name = "Holybound Grips", popularity = "2.5%" },
            { id = 219341, name = "Glyph-Etched Gauntlets", popularity = "1.9%" }
        },
        WAIST = {
            { id = 245965, name = "Durable Information Securing Container", popularity = "92.2%" },
            { id = 234501, name = "Portable Power Generator", popularity = "1.9%" },
            { id = 219339, name = "Glyph-Etched Binding", popularity = "0.7%" },
            { id = 237522, name = "BiSColossal Lifetether", popularity = "0.4%" },
            { id = 228845, name = "Sash of the Fierce Diva", popularity = "0.4%" }
        },
        LEGS = {
            { id = 229261, name = "Gale Sovereign's Pantaloons", popularity = "72.6%" },
            { id = 237636, name = "BiSTassets of Channeled Fury", popularity = "9.9%" },
            { id = 221129, name = "Divine Pyrewalkers", popularity = "4.6%" },
            { id = 246277, name = "Swampface's Oozewalkers", popularity = "3.4%" },
            { id = 219340, name = "Glyph-Etched Cuisses", popularity = "1.4%" }
        },
        FEET = {
            { id = 229264, name = "Gale Sovereign's Stormboots", popularity = "18.5%" },
            { id = 242483, name = "Greaves of the Wild Pair", popularity = "15.4%" },
            { id = 219335, name = "Glyph-Etched Stompers", popularity = "15.0%" },
            { id = 228862, name = "Shrapnel-Ridden Sabatons", popularity = "9.7%" },
            { id = 221152, name = "Silksteel Striders", popularity = "6.0%" }
        },
        FINGER1 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "50.4%" },
            { id = 228840, name = "Faded Championship Ring", popularity = "24.2%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "17.5%" },
            { id = 178871, name = "Bloodoath Signet", popularity = "10.3%" },
            { id = 221099, name = "Wick's Golden Loop", popularity = "7.9%" }
        },
        MAIN_HAND = {
            { id = 222439, name = "Everforged Dagger", popularity = "29.4%" },
            { id = 222445, name = "Charged Runeaxe", popularity = "21.7%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "6.9%" },
            { id = 178829, name = "Nathrian Ferula", popularity = "4.7%" },
            { id = 221122, name = "Hand of Beledar", popularity = "4.2%" }
        },
        OFF_HAND = {
            { id = 222432, name = "BiSEverforged Defender", popularity = "20.6%" },
            { id = 231311, name = "Frontman's Wondrous Wall", popularity = "15.4%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "8.1%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "5.9%" },
            { id = 228889, name = "Titan of Industry", popularity = "5.3%" }
        },
        TRINKET1 = {
            { id = 230186, name = "Mister Pick-Me-Up", popularity = "56.1%" },
            { id = 219305, name = "Carved Blazikon Wax", popularity = "24.9%" },
            { id = 230192, name = "Mug's Moxie Jug", popularity = "20.9%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "11.6%" },
            { id = 219306, name = "Burin of the Candle King", popularity = "11.5%" }
        },
        consumables = {
            { id = 212271, name = "Flask of Tempered Aggression", popularity = "47.9%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "19.1%" },
            { id = 212241, name = "Algari Mana Potion", popularity = "20.6%" },
            { id = 222720, name = "The Sushi Special", popularity = "26.9%" },
            { id = nil, name = "Earthliving Weapon", popularity = "62.5%" }
        }
    }
}
