-- Auto-generated by scraper
WishListData_Warlock = {
    AFFLICTION = {
        icon = "Interface/ICONS/Spell_Shadow_DeathCoil",
        talent = "CkQAAAAAAAAAAAAAAAAAAAAAAAzMzMzMjY2MMmNzMDzyAAAAmZMzyMjxyMzMLmxMDAYGLwAziRjZAMbglZAAAAAAAAwMsA",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "58.3%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "83.4%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "59.2%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "52.8%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "38.1%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "50.3%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "65.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "5.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "65.9%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "5.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        HEAD = {
            { id = 237700, name = "BiSInquisitor's Portal to Madness", popularity = "73.8%" },
            { id = 229325, name = "Spliced Fiendtrader's Transcendence", popularity = "7.1%" },
            { id = 242477, name = "Wasteland Devotee's Wrappings", popularity = "5.1%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "2.6%" },
            { id = 185795, name = "Cowl of Branching Fate", popularity = "2.5%" }
        },
        NECK = {
            { id = 178827, name = "Sin Stained Pendant", popularity = "20.7%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "19.2%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "11.5%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "7.9%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "7.2%" }
        },
        SHOULDERS = {
            { id = 237698, name = "BiSInquisitor's Gaze of Madness", popularity = "75.4%" },
            { id = 229323, name = "Spliced Fiendtrader's Loyal Servants", popularity = "8.2%" },
            { id = 185804, name = "Harmonious Spaulders", popularity = "2.6%" },
            { id = 246276, name = "Sinlight Shoulderpads", popularity = "2.0%" },
            { id = 221135, name = "Fanatic's Blackened Shoulderwraps", popularity = "1.4%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.7%" }
        },
        CHEST = {
            { id = 237703, name = "BiSInquisitor's Robes of Madness", popularity = "77.4%" },
            { id = 229328, name = "Spliced Fiendtrader's Surgical Gown", popularity = "6.8%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "3.1%" },
            { id = 221126, name = "Zealous Warden's Raiment", popularity = "2.0%" },
            { id = 237527, name = "Frock of Spirit's Reunion", popularity = "1.8%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "62.4%" },
            { id = 246279, name = "Fizzlefuse Cuffs", popularity = "9.4%" },
            { id = 242468, name = "Al'dani Attendant's Gauze", popularity = "5.1%" },
            { id = 237558, name = "Conjoined Glass Bracers", popularity = "4.2%" },
            { id = 185814, name = "Auctioneer's Counting Bracers", popularity = "4.1%" }
        },
        HANDS = {
            { id = 237701, name = "BiSInquisitor's Clutches of Madness", popularity = "57.0%" },
            { id = 242490, name = "Ancient Oracle's Caress", popularity = "7.5%" },
            { id = 178833, name = "Stonefiend Shaper's Mitts", popularity = "7.0%" },
            { id = 185793, name = "Cyphered Gloves", popularity = "5.9%" },
            { id = 237549, name = "Bloodwrath's Gnarled Claws", popularity = "5.1%" }
        },
        WAIST = {
            { id = 242664, name = "Durable Information Securing Container", popularity = "80.6%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "3.8%" },
            { id = 222816, name = "Consecrated Cord", popularity = "3.6%" },
            { id = 221158, name = "Burrower's Cinch", popularity = "3.1%" },
            { id = 178822, name = "Cord of the Dark Word", popularity = "1.5%" }
        },
        LEGS = {
            { id = 237699, name = "BiSInquisitor's Leggings of Madness", popularity = "76.3%" },
            { id = 229324, name = "Spliced Fiendtrader's Skin Tights", popularity = "6.8%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "3.9%" },
            { id = 221164, name = "Archaic Venomancer's Legwraps", popularity = "2.2%" },
            { id = 185799, name = "Hyperlight Leggings", popularity = "2.2%" }
        },
        FEET = {
            { id = 243305, name = "BiSInterloper's Silken Striders", popularity = "37.8%" },
            { id = 221149, name = "Membranous Slippers", popularity = "15.1%" },
            { id = 178831, name = "Slippers of Leavened Station", popularity = "9.1%" },
            { id = 237524, name = "Laced Lair-Steppers", popularity = "7.3%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "6.4%" }
        },
        FINGER1 = {
            { id = 242491, name = "Whispers of K'aresh", popularity = "28.8%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "25.9%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "24.6%" },
            { id = 231265, name = "The Jastor Diamond", popularity = "14.5%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "13.5%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "21.3%" },
            { id = 237728, name = "Voidglass Kris", popularity = "12.1%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "9.0%" },
            { id = 221150, name = "Arachnoid Soulcleaver", popularity = "7.0%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "6.5%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "58.1%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "2.2%" },
            { id = 237724, name = "Iris of the Dark Beyond", popularity = "0.9%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "0.8%" },
            { id = 238006, name = "Soulbearer's Censer", popularity = "0.7%" }
        },
        TRINKET1 = {
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "40.2%" },
            { id = 219308, name = "Signet of the Priory", popularity = "28.4%" },
            { id = 242402, name = "BiSAraz's Ritual Forge", popularity = "20.6%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "16.3%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "15.5%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "58.4%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "29.2%" },
            { id = 212265, name = "Tempered Potion", popularity = "64.1%" },
            { id = 222720, name = "The Sushi Special", popularity = "25.3%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "81.9%" }
        }
    },
    DEMONOLOGY = {
        icon = "Interface/ICONS/Spell_Shadow_Metamorphosis",
        talent = "CoQAAAAAAAAAAAAAAAAAAAAAAAmZmZmZEzmBmtZmZY2GAAAAAAAAAAzAGzYYBGYZYhGWYmxM2GzsNjZmZMmxwMzMzMwMAAA",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "61.0%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "83.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "86.7%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.7%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "54.2%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "41.0%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "54.0%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "61.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "8.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "61.6%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "8.3%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.1%" }
        },
        HEAD = {
            { id = 237700, name = "BiSInquisitor's Portal to Madness", popularity = "76.8%" },
            { id = 229325, name = "Spliced Fiendtrader's Transcendence", popularity = "5.7%" },
            { id = 242477, name = "Wasteland Devotee's Wrappings", popularity = "3.8%" },
            { id = 185795, name = "Cowl of Branching Fate", popularity = "2.3%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "1.9%" }
        },
        NECK = {
            { id = 252009, name = "Bloodstained Memento", popularity = "21.7%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "18.1%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "9.8%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "9.5%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "8.2%" }
        },
        SHOULDERS = {
            { id = 237698, name = "BiSInquisitor's Gaze of Madness", popularity = "77.6%" },
            { id = 229323, name = "Spliced Fiendtrader's Loyal Servants", popularity = "6.5%" },
            { id = 221135, name = "Fanatic's Blackened Shoulderwraps", popularity = "2.2%" },
            { id = 185804, name = "Harmonious Spaulders", popularity = "2.0%" },
            { id = 246276, name = "Sinlight Shoulderpads", popularity = "1.7%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.6%" }
        },
        CHEST = {
            { id = 237703, name = "BiSInquisitor's Robes of Madness", popularity = "74.4%" },
            { id = 229328, name = "Spliced Fiendtrader's Surgical Gown", popularity = "6.3%" },
            { id = 221126, name = "Zealous Warden's Raiment", popularity = "4.2%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "4.0%" },
            { id = 237527, name = "Frock of Spirit's Reunion", popularity = "2.4%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "56.9%" },
            { id = 242468, name = "Al'dani Attendant's Gauze", popularity = "8.0%" },
            { id = 246279, name = "Fizzlefuse Cuffs", popularity = "7.5%" },
            { id = 185814, name = "Auctioneer's Counting Bracers", popularity = "6.3%" },
            { id = 237534, name = "Singed Sievecuffs", popularity = "4.2%" }
        },
        HANDS = {
            { id = 237701, name = "Inquisitor's Clutches of Madness", popularity = "58.0%" },
            { id = 178833, name = "Stonefiend Shaper's Mitts", popularity = "7.2%" },
            { id = 242490, name = "Ancient Oracle's Caress", popularity = "5.8%" },
            { id = 237549, name = "BiSBloodwrath's Gnarled Claws", popularity = "4.7%" },
            { id = 185793, name = "Cyphered Gloves", popularity = "4.4%" }
        },
        WAIST = {
            { id = 242664, name = "Durable Information Securing Container", popularity = "80.2%" },
            { id = 222816, name = "Consecrated Cord", popularity = "3.9%" },
            { id = 221158, name = "Burrower's Cinch", popularity = "3.7%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "2.7%" },
            { id = 178822, name = "Cord of the Dark Word", popularity = "2.0%" }
        },
        LEGS = {
            { id = 237699, name = "BiSInquisitor's Leggings of Madness", popularity = "76.3%" },
            { id = 229324, name = "Spliced Fiendtrader's Skin Tights", popularity = "6.1%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "3.7%" },
            { id = 221164, name = "Archaic Venomancer's Legwraps", popularity = "3.1%" },
            { id = 185799, name = "Hyperlight Leggings", popularity = "2.1%" }
        },
        FEET = {
            { id = 243305, name = "BiSInterloper's Silken Striders", popularity = "35.3%" },
            { id = 221149, name = "Membranous Slippers", popularity = "11.3%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "10.5%" },
            { id = 178831, name = "Slippers of Leavened Station", popularity = "10.0%" },
            { id = 237524, name = "Laced Lair-Steppers", popularity = "6.3%" }
        },
        FINGER1 = {
            { id = 221136, name = "Devout Zealot's Ring", popularity = "31.5%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "18.6%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "17.8%" },
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "14.3%" },
            { id = 221141, name = "High Nerubian Signet", popularity = "12.9%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "28.7%" },
            { id = 237728, name = "Voidglass Kris", popularity = "7.9%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "7.2%" },
            { id = 222444, name = "Charged Hexsword", popularity = "6.7%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "6.2%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "47.4%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "1.8%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "1.8%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "1.5%" },
            { id = 237724, name = "Iris of the Dark Beyond", popularity = "1.2%" }
        },
        TRINKET1 = {
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "44.2%" },
            { id = 219308, name = "Signet of the Priory", popularity = "27.4%" },
            { id = 242494, name = "Lily of the Eternal Weave", popularity = "20.6%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "20.5%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "13.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "55.2%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "32.6%" },
            { id = 212265, name = "Tempered Potion", popularity = "60.9%" },
            { id = 222720, name = "The Sushi Special", popularity = "26.3%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "81.3%" }
        }
    },
    DESTRUCTION = {
        icon = "Interface/ICONS/Spell_Shadow_RainOfFire",
        talent = "CsQAAAAAAAAAAAAAAAAAAAAAAMMmxMzMjY2MMmNzMDzysZMmZmFzYWWmZGAAAAAzstMzsMPgFYgZxoxMAmNshBAAAAAAwMGzAA",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "62.6%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "81.7%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "59.8%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.2%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "39.4%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "41.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "64.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "64.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        HEAD = {
            { id = 237700, name = "BiSInquisitor's Portal to Madness", popularity = "76.7%" },
            { id = 242477, name = "Wasteland Devotee's Wrappings", popularity = "4.5%" },
            { id = 229325, name = "Spliced Fiendtrader's Transcendence", popularity = "4.2%" },
            { id = 221131, name = "Elysian Flame Crown", popularity = "2.5%" },
            { id = 237548, name = "Twilight Tyrant's Veil", popularity = "2.0%" }
        },
        NECK = {
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "23.0%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "15.8%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "9.6%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "8.5%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "8.0%" }
        },
        SHOULDERS = {
            { id = 237698, name = "BiSInquisitor's Gaze of Madness", popularity = "77.3%" },
            { id = 229323, name = "Spliced Fiendtrader's Loyal Servants", popularity = "4.6%" },
            { id = 185804, name = "Harmonious Spaulders", popularity = "2.4%" },
            { id = 246276, name = "Sinlight Shoulderpads", popularity = "2.2%" },
            { id = 221135, name = "Fanatic's Blackened Shoulderwraps", popularity = "1.9%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.7%" }
        },
        CHEST = {
            { id = 237703, name = "BiSInquisitor's Robes of Madness", popularity = "77.7%" },
            { id = 229328, name = "Spliced Fiendtrader's Surgical Gown", popularity = "4.5%" },
            { id = 234496, name = "Saboteur's Rubber Jacket", popularity = "3.6%" },
            { id = 237527, name = "Frock of Spirit's Reunion", popularity = "2.7%" },
            { id = 221126, name = "Zealous Warden's Raiment", popularity = "2.1%" }
        },
        WRISTS = {
            { id = 222815, name = "BiSConsecrated Cuffs", popularity = "58.8%" },
            { id = 246279, name = "Fizzlefuse Cuffs", popularity = "8.0%" },
            { id = 185814, name = "Auctioneer's Counting Bracers", popularity = "6.6%" },
            { id = 242468, name = "Al'dani Attendant's Gauze", popularity = "5.1%" },
            { id = 237558, name = "Conjoined Glass Bracers", popularity = "4.1%" }
        },
        HANDS = {
            { id = 237701, name = "BiSInquisitor's Clutches of Madness", popularity = "56.0%" },
            { id = 178833, name = "Stonefiend Shaper's Mitts", popularity = "7.4%" },
            { id = 242490, name = "Ancient Oracle's Caress", popularity = "7.3%" },
            { id = 237549, name = "Bloodwrath's Gnarled Claws", popularity = "5.7%" },
            { id = 185793, name = "Cyphered Gloves", popularity = "5.4%" }
        },
        WAIST = {
            { id = 242664, name = "Durable Information Securing Container", popularity = "78.9%" },
            { id = 222816, name = "Consecrated Cord", popularity = "4.4%" },
            { id = 221158, name = "Burrower's Cinch", popularity = "3.7%" },
            { id = 221121, name = "Honorbound Retainer's Sash", popularity = "3.6%" },
            { id = 237538, name = "BiSForgeweaver's Journal Holster", popularity = "1.6%" }
        },
        LEGS = {
            { id = 237699, name = "BiSInquisitor's Leggings of Madness", popularity = "76.6%" },
            { id = 229324, name = "Spliced Fiendtrader's Skin Tights", popularity = "4.5%" },
            { id = 234495, name = "Razorchoke Slacks", popularity = "3.6%" },
            { id = 221164, name = "Archaic Venomancer's Legwraps", popularity = "3.3%" },
            { id = 185799, name = "Hyperlight Leggings", popularity = "2.2%" }
        },
        FEET = {
            { id = 243305, name = "BiSInterloper's Silken Striders", popularity = "38.6%" },
            { id = 221149, name = "Membranous Slippers", popularity = "12.8%" },
            { id = 178831, name = "Slippers of Leavened Station", popularity = "9.1%" },
            { id = 237524, name = "Laced Lair-Steppers", popularity = "7.1%" },
            { id = 234497, name = "Nonconductive Kill-o-Socks", popularity = "6.7%" }
        },
        FINGER1 = {
            { id = 221136, name = "Devout Zealot's Ring", popularity = "30.0%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "25.0%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "20.0%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "17.5%" },
            { id = 231265, name = "The Jastor Diamond", popularity = "11.3%" }
        },
        MAIN_HAND = {
            { id = 222568, name = "Vagabond's Bounding Baton", popularity = "26.8%" },
            { id = 237728, name = "Voidglass Kris", popularity = "9.7%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "8.2%" },
            { id = 221165, name = "Unceremonious Bloodletter", popularity = "6.7%" },
            { id = 222444, name = "Charged Hexsword", popularity = "6.3%" }
        },
        OFF_HAND = {
            { id = 222566, name = "BiSVagabond's Torch", popularity = "48.9%" },
            { id = 246284, name = "Nathrian Reliquary", popularity = "1.8%" },
            { id = 185812, name = "Acoustically Alluring Censer", popularity = "1.4%" },
            { id = 237724, name = "Iris of the Dark Beyond", popularity = "1.4%" },
            { id = 221132, name = "Overflowing Umbral Pail", popularity = "1.2%" }
        },
        TRINKET1 = {
            { id = 242497, name = "Azhiccaran Parapodia", popularity = "47.1%" },
            { id = 219308, name = "Signet of the Priory", popularity = "24.7%" },
            { id = 242395, name = "Astral Antenna", popularity = "20.8%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "17.5%" },
            { id = 219312, name = "Empowering Crystal of Anub'ikkaj", popularity = "16.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "61.5%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "32.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "61.1%" },
            { id = 222720, name = "The Sushi Special", popularity = "28.5%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "81.7%" }
        }
    }
}
