-- Auto-generated by scraper
WishListData_Paladin = {
    HOLY = {
        icon = "Interface/ICONS/Spell_Holy_HolyBolt",
        talent = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAAYAAzAAAMAbjZYmxMjlZMLzMsMDmZbz0WMjZMzMMwslBAMwAbAbMLmxMLz2Mzs0AAAAsAYwmZghhB",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "26.9%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "40.7%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "57.8%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "57.9%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "76.2%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "60.6%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "50.9%" },
            MAINHAND = { id = 223778, name = "Authority of Fiery Resolve", popularity = "45.0%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "42.1%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "24.5%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "3.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "50.4%" },
            { id = 213455, name = "Quick Ruby", popularity = "45.5%" },
            { id = 213494, name = "Quick Onyx", popularity = "33.4%" },
            { id = 213470, name = "Quick Sapphire", popularity = "32.6%" }
        },
        HEAD = {
            { id = 237619, name = "BiSLightmane of the Lucent Battalion", popularity = "32.9%" },
            { id = 229244, name = "Aureate Sentry's Pledge", popularity = "31.5%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "5.6%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "5.5%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "4.8%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "16.0%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "13.9%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "11.3%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "10.2%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "7.3%" }
        },
        SHOULDERS = {
            { id = 229242, name = "Aureate Sentry's Roaring Will", popularity = "41.7%" },
            { id = 237617, name = "BiSChargers of the Lucent Battalion", popularity = "33.4%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "5.3%" },
            { id = 221155, name = "Swarm Monarch's Spaulders", popularity = "3.7%" },
            { id = 221203, name = "Reanimator's Pyreforged Shoulders", popularity = "3.1%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "95.9%" },
            { id = 222817, name = "Consecrated Cloak", popularity = "0.1%" }
        },
        CHEST = {
            { id = 237622, name = "BiSCuirass of the Lucent Battalion", popularity = "40.4%" },
            { id = 229247, name = "Aureate Sentry's Encasement", popularity = "34.2%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "4.8%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "4.5%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "4.2%" }
        },
        WRISTS = {
            { id = 222435, name = "Everforged Vambraces", popularity = "22.1%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "13.5%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "12.7%" },
            { id = 237561, name = "BiSYoke of Enveloping Hatred", popularity = "7.6%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "7.3%" }
        },
        HANDS = {
            { id = 229245, name = "Aureate Sentry's Gauntlets", popularity = "38.9%" },
            { id = 237620, name = "Protectors of the Lucent Battalion", popularity = "28.5%" },
            { id = 234504, name = "BiSJumpstarter's Scaffold-Scrapers", popularity = "10.1%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "6.2%" },
            { id = 237526, name = "Breached Containment Guards", popularity = "2.2%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "86.7%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "3.4%" },
            { id = 237550, name = "BiSFresh Ethereal Fetters", popularity = "1.0%" },
            { id = 242479, name = "Girdle of Absolute Faith", popularity = "0.9%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "0.9%" }
        },
        LEGS = {
            { id = 229243, name = "Aureate Sentry's Legguards", popularity = "42.0%" },
            { id = 237618, name = "BiSCuisses of the Lucent Battalion", popularity = "33.3%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "5.7%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "4.5%" },
            { id = 185798, name = "Quantum Leapers", popularity = "2.3%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "16.5%" },
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "11.4%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "9.8%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "8.8%" },
            { id = 159679, name = "Sabatons of Rampaging Elements", popularity = "5.9%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "21.9%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "19.4%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "16.4%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "15.7%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "12.2%" }
        },
        MAIN_HAND = {
            { id = 222444, name = "Charged Hexsword", popularity = "49.9%" },
            { id = 221150, name = "Arachnoid Soulcleaver", popularity = "6.8%" },
            { id = 221122, name = "Hand of Beledar", popularity = "5.1%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "4.5%" },
            { id = 231268, name = "Blastfurious Machete", popularity = "4.2%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "19.9%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "16.0%" },
            { id = 237723, name = "BiSWard of the Weaving-Beast", popularity = "11.2%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "8.1%" },
            { id = 185811, name = "Package Protector", popularity = "6.8%" }
        },
        TRINKET1 = {
            { id = 230186, name = "Mister Pick-Me-Up", popularity = "25.0%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "18.6%" },
            { id = 190958, name = "So'leah's Secret Technique", popularity = "17.0%" },
            { id = 219308, name = "Signet of the Priory", popularity = "16.1%" },
            { id = 219312, name = "Empowering Crystal of Anub'ikkaj", popularity = "15.6%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "47.4%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "18.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "17.2%" },
            { id = 222720, name = "The Sushi Special", popularity = "27.4%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "71.4%" }
        }
    },
    PROTECTION = {
        icon = "Interface/ICONS/Ability_Paladin_ShieldoftheTemplar",
        talent = "CIEAAAAAAAAAAAAAAAAAAAAAAsZMYWGLzMjZmZZbmZGzsNGGAAAAAAAAAA0WmZYYmZMmht2AgxADAD2GAAgZm2mlZbGAgNGAgZGzwYA",
        statprio = "Strength > Haste > Crit > Mastery > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "27.7%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "72.2%" },
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "56.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "57.7%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "79.8%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "51.8%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "51.2%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "42.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "48.2%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "18.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        gems = {
            { id = 213479, name = "Deadly Emerald", popularity = "51.0%" },
            { id = 213455, name = "Quick Ruby", popularity = "50.0%" },
            { id = 213482, name = "Masterful Emerald", popularity = "37.9%" },
            { id = 213494, name = "Quick Onyx", popularity = "30.4%" }
        },
        HEAD = {
            { id = 229244, name = "Aureate Sentry's Pledge", popularity = "32.1%" },
            { id = 237619, name = "BiSLightmane of the Lucent Battalion", popularity = "31.4%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "7.5%" },
            { id = 246283, name = "BiSCrown of Absolute Command", popularity = "6.3%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "4.1%" }
        },
        NECK = {
            { id = 178827, name = "Sin Stained Pendant", popularity = "18.8%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "17.4%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "13.9%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "10.8%" },
            { id = 185820, name = "BiSCabochon of the Infinite Flight", popularity = "8.8%" }
        },
        SHOULDERS = {
            { id = 229242, name = "Aureate Sentry's Roaring Will", popularity = "43.1%" },
            { id = 237617, name = "BiSChargers of the Lucent Battalion", popularity = "31.2%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "6.4%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "4.3%" },
            { id = 221203, name = "Reanimator's Pyreforged Shoulders", popularity = "2.9%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.4%" }
        },
        CHEST = {
            { id = 237622, name = "BiSCuirass of the Lucent Battalion", popularity = "39.7%" },
            { id = 229247, name = "Aureate Sentry's Encasement", popularity = "38.2%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "5.1%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "4.3%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "3.6%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "31.2%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "14.2%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "10.2%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "8.4%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "5.0%" }
        },
        HANDS = {
            { id = 229245, name = "Aureate Sentry's Gauntlets", popularity = "37.4%" },
            { id = 237620, name = "BiSProtectors of the Lucent Battalion", popularity = "31.9%" },
            { id = 234504, name = "BiSJumpstarter's Scaffold-Scrapers", popularity = "9.2%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "6.1%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "2.1%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "84.7%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "4.2%" },
            { id = 222431, name = "BiSEverforged Greatbelt", popularity = "2.3%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "1.8%" },
            { id = 242479, name = "Girdle of Absolute Faith", popularity = "0.9%" }
        },
        LEGS = {
            { id = 229243, name = "Aureate Sentry's Legguards", popularity = "43.6%" },
            { id = 237618, name = "BiSCuisses of the Lucent Battalion", popularity = "34.0%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "6.6%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "3.6%" },
            { id = 185798, name = "Quantum Leapers", popularity = "1.6%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "18.8%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "11.7%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "10.2%" },
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "10.0%" },
            { id = 159679, name = "Sabatons of Rampaging Elements", popularity = "6.8%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "24.6%" },
            { id = 242491, name = "BiSWhispers of K'aresh", popularity = "24.5%" },
            { id = 221136, name = "BiSDevout Zealot's Ring", popularity = "18.4%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "17.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "17.3%" }
        },
        MAIN_HAND = {
            { id = 222440, name = "Everforged Longsword", popularity = "31.7%" },
            { id = 221145, name = "Shipwrecker's Bludgeon", popularity = "12.1%" },
            { id = 242470, name = "Mandibular Bonewhacker", popularity = "8.5%" },
            { id = 185824, name = "Blade of Grievous Harm", popularity = "6.6%" },
            { id = 237813, name = "Factory-Issue Plexhammer", popularity = "5.3%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "29.1%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "16.5%" },
            { id = 237723, name = "BiSWard of the Weaving-Beast", popularity = "7.7%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "7.6%" },
            { id = 185811, name = "Package Protector", popularity = "6.7%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "50.7%" },
            { id = 219309, name = "Tome of Light's Devotion", popularity = "30.4%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "21.4%" },
            { id = 242401, name = "Brand of Ceaseless Ire", popularity = "12.1%" },
            { id = 232543, name = "Ringing Ritual Mud", popularity = "11.9%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "33.7%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "17.3%" },
            { id = 212265, name = "Tempered Potion", popularity = "40.6%" },
            { id = 222720, name = "The Sushi Special", popularity = "30.9%" },
            { id = nil, name = "Rite of Sanctification", popularity = "59.1%" }
        }
    },
    RETRIBUTION = {
        icon = "Interface/ICONS/Spell_Holy_AuraOfLight",
        talent = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAYAgRmltZmtltZGbGz2mZbAAAAAAY2aaGGmZsNDmthxsNzy2YGMDDLLsBAAAzMtNLz2MAgNgBAMMMA",
        statprio = "Strength > Mastery > Crit > Haste > Vers",
        enchants = {
            HEAD = { id = 239095, name = "Greater Rune of the Void Ritual", popularity = "39.5%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "81.8%" },
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "55.5%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "48.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "86.4%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "48.3%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.0%" },
            MAINHAND = { id = 223759, name = "Council's Guile", popularity = "31.2%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "66.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.6%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        gems = {
            { id = 213458, name = "Masterful Ruby", popularity = "57.2%" },
            { id = 213491, name = "Deadly Onyx", popularity = "43.5%" },
            { id = 213455, name = "Quick Ruby", popularity = "38.6%" },
            { id = 213479, name = "Deadly Emerald", popularity = "36.4%" }
        },
        HEAD = {
            { id = 229244, name = "Aureate Sentry's Pledge", popularity = "45.2%" },
            { id = 237619, name = "BiSLightmane of the Lucent Battalion", popularity = "33.9%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "3.3%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "2.8%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "2.3%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "23.9%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "14.2%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "12.5%" },
            { id = 221060, name = "Strapped Rescue-Keg", popularity = "10.5%" },
            { id = 228841, name = "Semi-Charmed Amulet", popularity = "7.2%" }
        },
        SHOULDERS = {
            { id = 229242, name = "Aureate Sentry's Roaring Will", popularity = "50.0%" },
            { id = 237617, name = "BiSChargers of the Lucent Battalion", popularity = "27.2%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "4.5%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "3.2%" },
            { id = 221155, name = "Swarm Monarch's Spaulders", popularity = "2.7%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.5%" }
        },
        CHEST = {
            { id = 229247, name = "Aureate Sentry's Encasement", popularity = "43.3%" },
            { id = 237622, name = "BiSCuirass of the Lucent Battalion", popularity = "39.1%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "5.0%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "2.6%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "1.8%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "56.7%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "9.5%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "5.5%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "5.3%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "3.6%" }
        },
        HANDS = {
            { id = 237620, name = "BiSProtectors of the Lucent Battalion", popularity = "36.7%" },
            { id = 229245, name = "Aureate Sentry's Gauntlets", popularity = "30.5%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "7.9%" },
            { id = 222437, name = "Everforged Gauntlets", popularity = "6.2%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "3.4%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "86.6%" },
            { id = 222431, name = "BiSEverforged Greatbelt", popularity = "4.2%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "2.1%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "1.1%" },
            { id = 237550, name = "Fresh Ethereal Fetters", popularity = "0.6%" }
        },
        LEGS = {
            { id = 229243, name = "Aureate Sentry's Legguards", popularity = "46.9%" },
            { id = 237618, name = "BiSCuisses of the Lucent Battalion", popularity = "36.9%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "4.6%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "1.4%" },
            { id = 237993, name = "Void-Scarred Captain's Greaves", popularity = "1.3%" }
        },
        FEET = {
            { id = 222429, name = "Everforged Sabatons", popularity = "21.5%" },
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "13.7%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "10.0%" },
            { id = 229246, name = "Aureate Sentry's Greaves", popularity = "7.4%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "6.6%" }
        },
        FINGER1 = {
            { id = 231265, name = "The Jastor Diamond", popularity = "38.7%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "17.7%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "16.6%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "15.9%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "15.8%" }
        },
        MAIN_HAND = {
            { id = 242487, name = "Fatebound Crusader", popularity = "18.0%" },
            { id = 234490, name = "Circuit Breaker", popularity = "13.8%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "10.9%" },
            { id = 222447, name = "Charged Claymore", popularity = "6.4%" },
            { id = 185810, name = "Skyreaver, Greataxe of the Keepers", popularity = "5.3%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "68.7%" },
            { id = 219308, name = "Signet of the Priory", popularity = "26.9%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "25.3%" },
            { id = 230027, name = "House of Cards", popularity = "17.2%" },
            { id = 246344, name = "Cursed Stone Idol", popularity = "8.0%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "55.5%" },
            { id = 211880, name = "Algari Healing Potion", popularity = "21.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "69.9%" },
            { id = 222720, name = "The Sushi Special", popularity = "19.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "79.8%" }
        }
    }
}
