-- Auto-generated by scraper
WishListData_Paladin = {
    HOLY = {
        icon = "Interface/ICONS/Spell_Holy_HolyBolt",
        talent = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAAYAAGAAgBYbMDzMmZsMjZZmhlZwMbbm2aMjZMzMMwslBAMwAbAbMLmxMLz2Mzs0AAAAsAYwCDmhhB",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "58.3%" },
            LEGS = { id = 222893, name = "Sunset Spellthread", popularity = "40.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "75.1%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "56.0%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "47.1%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "47.2%" },
            MAINHAND = { id = 223778, name = "Authority of Fiery Resolve", popularity = "31.0%" }
        },
        epic_gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "38.8%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "23.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "3.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" }
        },
        gems = {
            { id = 213746, name = "Elusive Blasphemite", popularity = "38.8%" },
            { id = 213743, name = "Culminating Blasphemite", popularity = "23.2%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "3.4%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.6%" }
        },
        HEAD = {
            { id = 237619, name = "BiSLightmane of the Lucent Battalion", popularity = "74.4%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "6.6%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "3.9%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "2.8%" },
            { id = 229244, name = "Aureate Sentry's Pledge", popularity = "1.9%" }
        },
        NECK = {
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "20.6%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "19.1%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "13.2%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "10.0%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "8.6%" }
        },
        SHOULDERS = {
            { id = 237617, name = "BiSChargers of the Lucent Battalion", popularity = "79.8%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "3.7%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "2.6%" },
            { id = 229242, name = "Aureate Sentry's Roaring Will", popularity = "2.2%" },
            { id = 221203, name = "Reanimator's Pyreforged Shoulders", popularity = "2.0%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.3%" }
        },
        CHEST = {
            { id = 237622, name = "BiSCuirass of the Lucent Battalion", popularity = "84.9%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "1.9%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "1.8%" },
            { id = 229247, name = "Aureate Sentry's Encasement", popularity = "1.7%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "1.2%" }
        },
        WRISTS = {
            { id = 222435, name = "Everforged Vambraces", popularity = "34.4%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "13.1%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "11.4%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "9.2%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "8.0%" }
        },
        HANDS = {
            { id = 237620, name = "Protectors of the Lucent Battalion", popularity = "67.5%" },
            { id = 234504, name = "BiSJumpstarter's Scaffold-Scrapers", popularity = "6.8%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "6.6%" },
            { id = 237526, name = "Breached Containment Guards", popularity = "4.0%" },
            { id = 229245, name = "Aureate Sentry's Gauntlets", popularity = "2.7%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "57.2%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "9.4%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "9.0%" },
            { id = 237550, name = "BiSFresh Ethereal Fetters", popularity = "5.6%" },
            { id = 246287, name = "Improvisational Girdle", popularity = "4.5%" }
        },
        LEGS = {
            { id = 237618, name = "BiSCuisses of the Lucent Battalion", popularity = "74.7%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "5.3%" },
            { id = 185798, name = "Quantum Leapers", popularity = "3.4%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "3.1%" },
            { id = 229243, name = "Aureate Sentry's Legguards", popularity = "3.0%" }
        },
        FEET = {
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "33.0%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "12.0%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "10.5%" },
            { id = 237551, name = "Sterilized Expulsion Boots", popularity = "7.0%" },
            { id = 222429, name = "Everforged Sabatons", popularity = "6.6%" }
        },
        FINGER1 = {
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "28.8%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "28.2%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "22.7%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "18.8%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "15.4%" }
        },
        MAIN_HAND = {
            { id = 222444, name = "Charged Hexsword", popularity = "60.4%" },
            { id = 237735, name = "BiSVoidglass Sovereign's Blade", popularity = "6.0%" },
            { id = 221150, name = "Arachnoid Soulcleaver", popularity = "5.0%" },
            { id = 221122, name = "Hand of Beledar", popularity = "4.7%" },
            { id = 237736, name = "Overclocked Plexhammer", popularity = "4.5%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "49.5%" },
            { id = 237723, name = "BiSWard of the Weaving-Beast", popularity = "11.7%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "10.0%" },
            { id = 185811, name = "Package Protector", popularity = "6.1%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "5.3%" }
        },
        TRINKET1 = {
            { id = 190958, name = "So'leah's Secret Technique", popularity = "38.7%" },
            { id = 242393, name = "Loom'ithar's Living Silk", popularity = "29.2%" },
            { id = 219312, name = "Empowering Crystal of Anub'ikkaj", popularity = "20.9%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "16.0%" },
            { id = 242395, name = "Astral Antenna", popularity = "14.8%" }
        },
        consumables = {
            { id = 212274, name = "Flask of Tempered Swiftness", popularity = "35.0%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "16.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "12.3%" },
            { id = 222720, name = "The Sushi Special", popularity = "28.8%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "65.5%" }
        }
    },
    PROTECTION = {
        icon = "Interface/ICONS/Ability_Paladin_ShieldoftheTemplar",
        talent = "CIEAAAAAAAAAAAAAAAAAAAAAAsZMYWGLzMjZmZZbmZGzsNGGAAgBAAAAAAg2amZWMMDGzY2aDAGDMAAbDAAAAYmZZbptZGLMYAYwMMG",
        statprio = "Strength > Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "65.2%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "73.0%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "81.2%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "58.2%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "57.7%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "40.4%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "41.8%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "45.5%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "19.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "45.5%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "19.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        HEAD = {
            { id = 237619, name = "BiSLightmane of the Lucent Battalion", popularity = "72.1%" },
            { id = 246283, name = "BiSCrown of Absolute Command", popularity = "10.2%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "4.7%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "2.0%" },
            { id = 229244, name = "Aureate Sentry's Pledge", popularity = "1.8%" }
        },
        NECK = {
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "33.9%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "20.4%" },
            { id = 185820, name = "BiSCabochon of the Infinite Flight", popularity = "12.6%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "8.7%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "3.9%" }
        },
        SHOULDERS = {
            { id = 237617, name = "BiSChargers of the Lucent Battalion", popularity = "69.4%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "10.0%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "5.6%" },
            { id = 221203, name = "Reanimator's Pyreforged Shoulders", popularity = "2.3%" },
            { id = 229242, name = "Aureate Sentry's Roaring Will", popularity = "1.8%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.6%" }
        },
        CHEST = {
            { id = 237622, name = "BiSCuirass of the Lucent Battalion", popularity = "86.3%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "2.2%" },
            { id = 229247, name = "Aureate Sentry's Encasement", popularity = "1.7%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "1.4%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "1.2%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "48.0%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "12.7%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "9.7%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "7.3%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "6.0%" }
        },
        HANDS = {
            { id = 237620, name = "BiSProtectors of the Lucent Battalion", popularity = "79.2%" },
            { id = 234504, name = "BiSJumpstarter's Scaffold-Scrapers", popularity = "4.6%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "3.1%" },
            { id = 229245, name = "Aureate Sentry's Gauntlets", popularity = "2.0%" },
            { id = 237526, name = "Breached Containment Guards", popularity = "1.9%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "46.8%" },
            { id = 222431, name = "BiSEverforged Greatbelt", popularity = "23.1%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "9.1%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "5.5%" },
            { id = 246287, name = "Improvisational Girdle", popularity = "3.3%" }
        },
        LEGS = {
            { id = 237618, name = "BiSCuisses of the Lucent Battalion", popularity = "79.8%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "4.3%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "2.6%" },
            { id = 229243, name = "Aureate Sentry's Legguards", popularity = "2.6%" },
            { id = 185798, name = "Quantum Leapers", popularity = "1.8%" }
        },
        FEET = {
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "32.8%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "17.4%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "9.5%" },
            { id = 211031, name = "Secret-Dredger's Sabatons", popularity = "6.7%" },
            { id = 222429, name = "Everforged Sabatons", popularity = "6.4%" }
        },
        FINGER1 = {
            { id = 221136, name = "BiSDevout Zealot's Ring", popularity = "39.1%" },
            { id = 242491, name = "BiSWhispers of K'aresh", popularity = "30.3%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "28.2%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "20.9%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "14.7%" }
        },
        MAIN_HAND = {
            { id = 222440, name = "Everforged Longsword", popularity = "49.5%" },
            { id = 237813, name = "Factory-Issue Plexhammer", popularity = "9.0%" },
            { id = 185824, name = "Blade of Grievous Harm", popularity = "8.5%" },
            { id = 221145, name = "Shipwrecker's Bludgeon", popularity = "7.8%" },
            { id = 242470, name = "Mandibular Bonewhacker", popularity = "5.7%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "60.0%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "10.3%" },
            { id = 237723, name = "BiSWard of the Weaving-Beast", popularity = "7.3%" },
            { id = 185811, name = "Package Protector", popularity = "7.0%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "4.4%" }
        },
        TRINKET1 = {
            { id = 242401, name = "Brand of Ceaseless Ire", popularity = "36.7%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "34.4%" },
            { id = 219309, name = "Tome of Light's Devotion", popularity = "19.4%" },
            { id = 190958, name = "So'leah's Secret Technique", popularity = "17.6%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "17.0%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "30.0%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "21.7%" },
            { id = 212265, name = "Tempered Potion", popularity = "41.0%" },
            { id = 222720, name = "The Sushi Special", popularity = "35.2%" },
            { id = nil, name = "Rite of Sanctification", popularity = "85.5%" }
        }
    },
    RETRIBUTION = {
        icon = "Interface/ICONS/Spell_Holy_AuraOfLight",
        talent = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAYAgRmltZmtltZGbGz2mZbAAAAAAY2aaGGmZsNDmthxsNzy2YGMDDLLsBAAAzMtNLz2MAgNgBAMMMA",
        statprio = "Strength > Crit > Mastery > Haste > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "58.3%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "78.8%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "85.0%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "48.3%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "53.4%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "45.3%" },
            MAINHAND = { id = 223759, name = "Council's Guile", popularity = "37.8%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "59.2%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.2%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "59.2%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.2%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" },
            { id = 213740, name = "Insightful Blasphemite", popularity = "0.2%" }
        },
        HEAD = {
            { id = 237619, name = "BiSLightmane of the Lucent Battalion", popularity = "83.2%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "3.1%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "2.5%" },
            { id = 229244, name = "Aureate Sentry's Pledge", popularity = "2.0%" },
            { id = 237535, name = "Artoshion's Abyssal Stare", popularity = "1.1%" }
        },
        NECK = {
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "32.3%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "14.6%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "14.3%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "6.8%" },
            { id = 237963, name = "Void-Scarred Brooch", popularity = "6.0%" }
        },
        SHOULDERS = {
            { id = 237617, name = "BiSChargers of the Lucent Battalion", popularity = "54.7%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "12.0%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "8.3%" },
            { id = 222436, name = "Everforged Pauldrons", popularity = "4.1%" },
            { id = 211034, name = "Secret-Dredger's Mantle", popularity = "3.4%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.3%" }
        },
        CHEST = {
            { id = 237622, name = "BiSCuirass of the Lucent Battalion", popularity = "85.0%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "3.1%" },
            { id = 237528, name = "Manaforged Displacement Chassis", popularity = "1.8%" },
            { id = 229247, name = "Aureate Sentry's Encasement", popularity = "1.6%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "1.4%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "64.6%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "7.7%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "6.6%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "3.8%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "3.8%" }
        },
        HANDS = {
            { id = 237620, name = "BiSProtectors of the Lucent Battalion", popularity = "84.0%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "3.0%" },
            { id = 237991, name = "Void-Scarred Captain's Handguards", popularity = "1.5%" },
            { id = 229245, name = "Aureate Sentry's Gauntlets", popularity = "1.5%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "1.4%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "50.1%" },
            { id = 222431, name = "BiSEverforged Greatbelt", popularity = "27.2%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "5.5%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "4.2%" },
            { id = 237550, name = "Fresh Ethereal Fetters", popularity = "3.2%" }
        },
        LEGS = {
            { id = 237618, name = "BiSCuisses of the Lucent Battalion", popularity = "86.2%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "2.2%" },
            { id = 229243, name = "Aureate Sentry's Legguards", popularity = "2.2%" },
            { id = 237993, name = "Void-Scarred Captain's Greaves", popularity = "1.2%" },
            { id = 211033, name = "Secret-Dredger's Legguards", popularity = "0.9%" }
        },
        FEET = {
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "38.2%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "14.9%" },
            { id = 237551, name = "Sterilized Expulsion Boots", popularity = "9.0%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "6.5%" },
            { id = 211031, name = "Secret-Dredger's Sabatons", popularity = "6.3%" }
        },
        FINGER1 = {
            { id = 221136, name = "Devout Zealot's Ring", popularity = "37.4%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "35.7%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "18.3%" },
            { id = 237567, name = "BiSLogic Gate: Alpha", popularity = "15.0%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "13.5%" }
        },
        MAIN_HAND = {
            { id = 222443, name = "Everforged Greataxe", popularity = "34.3%" },
            { id = 222447, name = "Charged Claymore", popularity = "21.9%" },
            { id = 242487, name = "Fatebound Crusader", popularity = "10.7%" },
            { id = 234490, name = "Circuit Breaker", popularity = "7.0%" },
            { id = 185810, name = "Skyreaver, Greataxe of the Keepers", popularity = "5.5%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "51.6%" },
            { id = 219308, name = "Signet of the Priory", popularity = "28.7%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "24.3%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "20.6%" },
            { id = 246344, name = "Cursed Stone Idol", popularity = "20.5%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "48.0%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "23.5%" },
            { id = 212265, name = "Tempered Potion", popularity = "62.2%" },
            { id = 222720, name = "The Sushi Special", popularity = "23.1%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "75.7%" }
        }
    }
}
