-- Auto-generated by scraper
WishListData_Warrior = {
    PROTECTION = {
        icon = "Interface/ICONS/Ability_Warrior_DefensiveStance",
        talent = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAAgxMMzMzMzMbmZWGMGjGzyYGGLjZmhtZmxMwwAAAAAAALDAwM2AMwGssY0YGAzCMbMjZA",
        statprio = "Strength > Haste > Crit > Vers > Mastery",
        enchants = {
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "71.8%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "49.3%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "78.6%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "59.4%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "62.4%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "45.9%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "52.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "50.7%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "11.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "50.7%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "11.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.4%" }
        },
        HEAD = {
            { id = 237610, name = "BiSLiving Weapon's Faceshield", popularity = "79.6%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "3.6%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "2.4%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "2.3%" },
            { id = 229235, name = "Enforcer's Backalley Faceshield", popularity = "2.1%" }
        },
        NECK = {
            { id = 185820, name = "BiSCabochon of the Infinite Flight", popularity = "36.4%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "16.6%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "9.4%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "8.6%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "5.1%" }
        },
        SHOULDERS = {
            { id = 237608, name = "BiSLiving Weapon's Ramparts", popularity = "81.1%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "3.5%" },
            { id = 229233, name = "Enforcer's Backalley Shoulderplates", popularity = "2.3%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "1.9%" },
            { id = 221203, name = "Reanimator's Pyreforged Shoulders", popularity = "1.7%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.7%" }
        },
        CHEST = {
            { id = 237613, name = "Living Weapon's Bulwark", popularity = "55.3%" },
            { id = 221161, name = "BiSExperimental Goresilk Chestguard", popularity = "11.9%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "10.0%" },
            { id = 221139, name = "Dark Priest's Carapace", popularity = "4.8%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "2.7%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "39.9%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "13.7%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "12.9%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "6.9%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "6.5%" }
        },
        HANDS = {
            { id = 237611, name = "BiSLiving Weapon's Crushers", popularity = "78.0%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "4.2%" },
            { id = 229236, name = "Enforcer's Backalley Crushers", popularity = "3.0%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "2.5%" },
            { id = 211032, name = "Secret-Dredger's Gauntlets", popularity = "1.7%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "57.9%" },
            { id = 222431, name = "BiSEverforged Greatbelt", popularity = "13.1%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "9.5%" },
            { id = 246287, name = "Improvisational Girdle", popularity = "5.0%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "3.0%" }
        },
        LEGS = {
            { id = 237609, name = "BiSLiving Weapon's Legguards", popularity = "73.5%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "5.6%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "3.3%" },
            { id = 229234, name = "Enforcer's Backalley Chausses", popularity = "3.0%" },
            { id = 185798, name = "Quantum Leapers", popularity = "2.9%" }
        },
        FEET = {
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "27.9%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "12.7%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "12.3%" },
            { id = 237990, name = "Void-Scarred Captain's Sollerets", popularity = "7.7%" },
            { id = 211031, name = "Secret-Dredger's Sabatons", popularity = "6.3%" }
        },
        FINGER1 = {
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "40.1%" },
            { id = 221136, name = "Devout Zealot's Ring", popularity = "31.2%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "25.0%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "16.1%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "10.2%" }
        },
        MAIN_HAND = {
            { id = 222440, name = "Everforged Longsword", popularity = "46.0%" },
            { id = 221145, name = "Shipwrecker's Bludgeon", popularity = "7.6%" },
            { id = 185824, name = "Blade of Grievous Harm", popularity = "7.5%" },
            { id = 222451, name = "Charged Slicer", popularity = "7.2%" },
            { id = 242470, name = "Mandibular Bonewhacker", popularity = "7.1%" }
        },
        OFF_HAND = {
            { id = 222432, name = "Everforged Defender", popularity = "64.2%" },
            { id = 242493, name = "Starlit Safeguard", popularity = "6.6%" },
            { id = 237723, name = "BiSWard of the Weaving-Beast", popularity = "6.5%" },
            { id = 185811, name = "Package Protector", popularity = "4.5%" },
            { id = 221117, name = "Sanctified Priory Wall", popularity = "4.2%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "37.9%" },
            { id = 242401, name = "Brand of Ceaseless Ire", popularity = "33.3%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "19.2%" },
            { id = 219309, name = "Tome of Light's Devotion", popularity = "17.0%" },
            { id = 190958, name = "So'leah's Secret Technique", popularity = "16.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "34.7%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "26.8%" },
            { id = 212265, name = "Tempered Potion", popularity = "35.7%" },
            { id = 222720, name = "The Sushi Special", popularity = "37.5%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "68.8%" }
        }
    },
    ARMS = {
        icon = "Interface/ICONS/Ability_Warrior_SavageBlow",
        talent = "CcEAAAAAAAAAAAAAAAAAAAAAAghZmxMmxMz2stsMmBAAAYw0wYWGzsZsMmZGbmZGmBDDAAAAAAAzY2GMgtYAbmxwGMwMsRDYBA",
        statprio = "Strength > Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "42.0%" },
            LEGS = { id = 219908, name = "Defender's Armor Kit", popularity = "41.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "75.2%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "50.1%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "31.8%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "48.4%" },
            MAINHAND = { id = 223759, name = "Council's Guile", popularity = "35.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "56.1%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.2%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "56.1%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "7.2%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        HEAD = {
            { id = 237610, name = "BiSLiving Weapon's Faceshield", popularity = "73.6%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "5.8%" },
            { id = 229235, name = "Enforcer's Backalley Faceshield", popularity = "3.2%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "2.8%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "2.7%" }
        },
        NECK = {
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "30.1%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "11.3%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "9.3%" },
            { id = 237963, name = "Void-Scarred Brooch", popularity = "7.8%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "7.7%" }
        },
        SHOULDERS = {
            { id = 237608, name = "BiSLiving Weapon's Ramparts", popularity = "70.4%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "7.1%" },
            { id = 229233, name = "Enforcer's Backalley Shoulderplates", popularity = "4.0%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "3.2%" },
            { id = 237994, name = "Void-Scarred Captain's Epaulettes", popularity = "2.7%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.5%" }
        },
        CHEST = {
            { id = 237613, name = "BiSLiving Weapon's Bulwark", popularity = "73.9%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "5.4%" },
            { id = 229238, name = "Enforcer's Backalley Vestplate", popularity = "2.9%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "2.5%" },
            { id = 221139, name = "Dark Priest's Carapace", popularity = "2.5%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "53.9%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "10.5%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "6.0%" },
            { id = 237545, name = "Discarded Nutrient Shackles", popularity = "5.5%" },
            { id = 211036, name = "Secret-Dredger's Armplates", popularity = "5.1%" }
        },
        HANDS = {
            { id = 237611, name = "BiSLiving Weapon's Crushers", popularity = "76.1%" },
            { id = 229236, name = "Enforcer's Backalley Crushers", popularity = "4.1%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "3.1%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "3.1%" },
            { id = 237526, name = "Breached Containment Guards", popularity = "3.0%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "63.7%" },
            { id = 222431, name = "BiSEverforged Greatbelt", popularity = "13.9%" },
            { id = 234505, name = "Venture Contractor's Floodlight", popularity = "6.6%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "2.8%" },
            { id = 246287, name = "Improvisational Girdle", popularity = "2.2%" }
        },
        LEGS = {
            { id = 237609, name = "BiSLiving Weapon's Legguards", popularity = "72.3%" },
            { id = 229234, name = "Enforcer's Backalley Chausses", popularity = "5.3%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "3.6%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "3.5%" },
            { id = 185798, name = "Quantum Leapers", popularity = "3.4%" }
        },
        FEET = {
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "31.4%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "11.9%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "9.1%" },
            { id = 211031, name = "Secret-Dredger's Sabatons", popularity = "7.8%" },
            { id = 237551, name = "Sterilized Expulsion Boots", popularity = "6.6%" }
        },
        FINGER1 = {
            { id = 221136, name = "Devout Zealot's Ring", popularity = "38.8%" },
            { id = 246281, name = "Ring of the Panoply", popularity = "25.3%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "16.8%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "13.8%" },
            { id = 185813, name = "BiSSignet of Collapsing Stars", popularity = "11.5%" }
        },
        MAIN_HAND = {
            { id = 222447, name = "Charged Claymore", popularity = "32.9%" },
            { id = 222443, name = "Everforged Greataxe", popularity = "24.4%" },
            { id = 242487, name = "Fatebound Crusader", popularity = "10.0%" },
            { id = 185810, name = "Skyreaver, Greataxe of the Keepers", popularity = "5.1%" },
            { id = 234490, name = "Circuit Breaker", popularity = "5.0%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "39.5%" },
            { id = 246344, name = "Cursed Stone Idol", popularity = "37.1%" },
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "28.3%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "16.1%" },
            { id = 242394, name = "Eradicating Arcanocore", popularity = "10.6%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "53.0%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "22.0%" },
            { id = 212265, name = "Tempered Potion", popularity = "49.4%" },
            { id = 222720, name = "The Sushi Special", popularity = "31.0%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "65.1%" }
        }
    },
    FURY = {
        icon = "Interface/ICONS/Ability_Warrior_BattleShout",
        talent = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQjhxsZmhZWGMzCzMzYGmhZ22mZMzMLAzMzYmxywwMzMAAAIGbbDsAGwMMBGsBA",
        statprio = "Strength > Mastery > Haste > Vers > Crit",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "51.8%" },
            LEGS = { id = 219908, name = "Defender's Armor Kit", popularity = "50.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "84.3%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "59.1%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "39.3%" },
            RINGS = { id = 223677, name = "Radiant Mastery", popularity = "54.3%" },
            MAINHAND = { id = 223768, name = "Oathsworn's Tenacity", popularity = "47.2%" },
            OFFHAND = { id = 223768, name = "Oathsworn's Tenacity", popularity = "45.1%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "62.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.7%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "62.3%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "6.7%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        HEAD = {
            { id = 237610, name = "Living Weapon's Faceshield", popularity = "61.5%" },
            { id = 178812, name = "Wing Commander's Helmet", popularity = "13.4%" },
            { id = 246283, name = "Crown of Absolute Command", popularity = "4.5%" },
            { id = 221146, name = "Soaring Behemoth's Greathelm", popularity = "3.5%" },
            { id = 238028, name = "BiSBone-Melted Faceplate", popularity = "2.7%" }
        },
        NECK = {
            { id = 178827, name = "Sin Stained Pendant", popularity = "29.3%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "19.7%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "11.5%" },
            { id = 237568, name = "BiSChrysalis of Sundered Souls", popularity = "7.4%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "4.1%" }
        },
        SHOULDERS = {
            { id = 237608, name = "BiSLiving Weapon's Ramparts", popularity = "79.0%" },
            { id = 246286, name = "Spaulders of Unleashed Pride", popularity = "4.4%" },
            { id = 221155, name = "Swarm Monarch's Spaulders", popularity = "2.7%" },
            { id = 229233, name = "Enforcer's Backalley Shoulderplates", popularity = "1.8%" },
            { id = 185803, name = "Stoneflesh Spaulders", popularity = "1.8%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.5%" }
        },
        CHEST = {
            { id = 237613, name = "BiSLiving Weapon's Bulwark", popularity = "82.1%" },
            { id = 221161, name = "Experimental Goresilk Chestguard", popularity = "2.8%" },
            { id = 234506, name = "Muckdiver's Wading Plate", popularity = "2.2%" },
            { id = 178814, name = "Breastplate of Otherworldly Influence", popularity = "1.9%" },
            { id = 229238, name = "Enforcer's Backalley Vestplate", popularity = "1.7%" }
        },
        WRISTS = {
            { id = 222435, name = "BiSEverforged Vambraces", popularity = "61.8%" },
            { id = 185815, name = "Vambraces of Verification", popularity = "7.3%" },
            { id = 221118, name = "Flameforged Armguard", popularity = "5.0%" },
            { id = 242475, name = "Eco-Dome Access Bands", popularity = "4.8%" },
            { id = 237561, name = "Yoke of Enveloping Hatred", popularity = "4.4%" }
        },
        HANDS = {
            { id = 237611, name = "BiSLiving Weapon's Crushers", popularity = "76.5%" },
            { id = 234504, name = "Jumpstarter's Scaffold-Scrapers", popularity = "5.4%" },
            { id = 221151, name = "Devourer's Gauntlets", popularity = "3.6%" },
            { id = 229236, name = "Enforcer's Backalley Crushers", popularity = "2.2%" },
            { id = 185792, name = "Achillite's Unbreakable Grip", popularity = "2.2%" }
        },
        WAIST = {
            { id = 245966, name = "Durable Information Securing Container", popularity = "64.6%" },
            { id = 237550, name = "Fresh Ethereal Fetters", popularity = "7.7%" },
            { id = 222431, name = "Everforged Greatbelt", popularity = "6.6%" },
            { id = 221133, name = "Girdle of Somber Ploys", popularity = "5.4%" },
            { id = 242479, name = "Girdle of Absolute Faith", popularity = "3.8%" }
        },
        LEGS = {
            { id = 237609, name = "BiSLiving Weapon's Legguards", popularity = "80.5%" },
            { id = 246278, name = "Overpressure Platelegs", popularity = "3.9%" },
            { id = 178818, name = "Halkias's Towering Pillars", popularity = "2.3%" },
            { id = 229234, name = "Enforcer's Backalley Chausses", popularity = "1.9%" },
            { id = 211033, name = "Secret-Dredger's Legguards", popularity = "1.6%" }
        },
        FEET = {
            { id = 243307, name = "BiSInterloper's Plated Sabatons", popularity = "39.3%" },
            { id = 185787, name = "Implacable Weatherproof Treads", popularity = "12.8%" },
            { id = 221123, name = "Devoted Plate Walkers", popularity = "10.3%" },
            { id = 211031, name = "Secret-Dredger's Sabatons", popularity = "7.6%" },
            { id = 237551, name = "Sterilized Expulsion Boots", popularity = "6.2%" }
        },
        FINGER1 = {
            { id = 178824, name = "BiSSignet of the False Accuser", popularity = "42.1%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "31.1%" },
            { id = 221200, name = "BiSRadiant Necromancer's Band", popularity = "26.4%" },
            { id = 221141, name = "High Nerubian Signet", popularity = "15.1%" },
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "11.7%" }
        },
        MAIN_HAND = {
            { id = 222447, name = "Charged Claymore", popularity = "33.4%" },
            { id = 222443, name = "BiSEverforged Greataxe", popularity = "25.2%" },
            { id = 234490, name = "BiSCircuit Breaker", popularity = "9.0%" },
            { id = 242487, name = "Fatebound Crusader", popularity = "7.1%" },
            { id = 221127, name = "Emberbrand Zweihander", popularity = "6.3%" }
        },
        OFF_HAND = {
            { id = 234490, name = "BiSCircuit Breaker", popularity = "20.2%" },
            { id = 222447, name = "Charged Claymore", popularity = "11.2%" },
            { id = 237737, name = "Photon Sabre Prime", popularity = "9.9%" },
            { id = 242487, name = "Fatebound Crusader", popularity = "9.2%" },
            { id = 222443, name = "BiSEverforged Greataxe", popularity = "8.5%" }
        },
        TRINKET1 = {
            { id = 219314, name = "Ara-Kara Sacbrood", popularity = "42.7%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "31.6%" },
            { id = 246344, name = "Cursed Stone Idol", popularity = "27.4%" },
            { id = 242395, name = "Astral Antenna", popularity = "18.8%" },
            { id = 242394, name = "BiSEradicating Arcanocore", popularity = "18.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "64.6%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "30.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "61.9%" },
            { id = 222720, name = "The Sushi Special", popularity = "16.4%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "70.4%" }
        }
    }
}
