-- Auto-generated by scraper
WishListData_Demonhunter = {
    HAVOC = {
        icon = "Interface/ICONS/Ability_DemonHunter_SpecDPS",
        talent = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZmZmZmZMzMjhJDzAAAAAAAmFjxMjZmZbMzGWmZwYYssNbzghx2GTYGzMDDL",
        statprio = "Crit > Mastery > Haste > Vers",
        enchants = {
            BACK = { id = 223731, name = "Chant of Winged Grace", popularity = "57.6%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "84.1%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "87.4%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "71.5%" },
            WRIST = { id = 223713, name = "Chant of Armored Avoidance", popularity = "56.8%" },
            RINGS = { id = 223662, name = "Radiant Critical Strike", popularity = "59.9%" },
            MAINHAND = { id = 223759, name = "Council's Guile", popularity = "54.4%" },
            OFFHAND = { id = 223759, name = "Council's Guile", popularity = "48.2%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "72.0%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "2.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "72.0%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "2.9%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.3%" }
        },
        HEAD = {
            { id = 237691, name = "BiSCharhound's Vicious Scalp", popularity = "75.2%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "8.6%" },
            { id = 237525, name = "Irradiated Impurity Filter", popularity = "2.8%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "2.2%" },
            { id = 211017, name = "Treasure-Seeker's Helm", popularity = "1.9%" }
        },
        NECK = {
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "38.2%" },
            { id = 185842, name = "Ornately Engraved Amplifier", popularity = "18.9%" },
            { id = 251880, name = "Momma's Mega Medallion", popularity = "10.6%" },
            { id = 242406, name = "BiSSalhadaar's Folly", popularity = "8.0%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "5.0%" }
        },
        SHOULDERS = {
            { id = 237689, name = "BiSCharhound's Vicious Hornguards", popularity = "84.5%" },
            { id = 185802, name = "Breakbeat Shoulderguards", popularity = "3.5%" },
            { id = 242486, name = "Mantle of Wounded Fate", popularity = "2.0%" },
            { id = 237552, name = "Deathbound Shoulderpads", popularity = "1.4%" },
            { id = 219330, name = "Rune-Branded Mantle", popularity = "1.1%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.6%" }
        },
        CHEST = {
            { id = 237694, name = "BiSCharhound's Vicious Bindings", popularity = "90.7%" },
            { id = 246273, name = "Vest of Refracted Shadows", popularity = "1.5%" },
            { id = 237541, name = "Darksorrow's Corrupted Carapace", popularity = "0.6%" },
            { id = 229319, name = "Fel-Dealer's Soul Engine", popularity = "0.6%" },
            { id = 237973, name = "Void-Scarred Blade's Jerkin", popularity = "0.6%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "71.4%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "6.9%" },
            { id = 185817, name = "Bracers of Autonomous Classification", popularity = "4.9%" },
            { id = 237546, name = "Bindings of Lost Essence", popularity = "3.3%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "2.6%" }
        },
        HANDS = {
            { id = 237692, name = "BiSCharhound's Vicious Felclaws", popularity = "86.7%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "1.9%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "1.4%" },
            { id = 211016, name = "Treasure-Seeker's Grips", popularity = "1.3%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "1.1%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "43.7%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "18.3%" },
            { id = 237533, name = "BiSAtomic Phasebelt", popularity = "13.6%" },
            { id = 221134, name = "Shadow Congregant's Belt", popularity = "8.3%" },
            { id = 185809, name = "Venza's Powderbelt", popularity = "3.4%" }
        },
        LEGS = {
            { id = 237690, name = "BiSCharhound's Vicious Hidecoat", popularity = "70.5%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "10.1%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "5.3%" },
            { id = 185801, name = "Anomalous Starlit Breeches", popularity = "3.4%" },
            { id = 178819, name = "Skyterror's Stonehide Leggings", popularity = "2.2%" }
        },
        FEET = {
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "51.6%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "14.1%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "6.7%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "4.2%" },
            { id = 211015, name = "Treasure-Seeker's Boots", popularity = "4.0%" }
        },
        FINGER1 = {
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "41.4%" },
            { id = 221136, name = "BiSDevout Zealot's Ring", popularity = "33.0%" },
            { id = 237567, name = "BiSLogic Gate: Alpha", popularity = "28.6%" },
            { id = 178824, name = "Signet of the False Accuser", popularity = "20.0%" },
            { id = 221200, name = "Radiant Necromancer's Band", popularity = "9.6%" }
        },
        MAIN_HAND = {
            { id = 222441, name = "BiSEverforged Warglaive", popularity = "41.8%" },
            { id = 237738, name = "Unbound Training Claws", popularity = "9.7%" },
            { id = 185780, name = "BiSInterrogator's Flensing Blade", popularity = "9.4%" },
            { id = 222440, name = "Everforged Longsword", popularity = "9.3%" },
            { id = 185778, name = "First Fist of the So Cartel", popularity = "6.3%" }
        },
        OFF_HAND = {
            { id = 222441, name = "BiSEverforged Warglaive", popularity = "43.7%" },
            { id = 222440, name = "Everforged Longsword", popularity = "12.1%" },
            { id = 237727, name = "BiSCollapsing Phaseblades", popularity = "10.2%" },
            { id = 185780, name = "BiSInterrogator's Flensing Blade", popularity = "6.6%" },
            { id = 237738, name = "Unbound Training Claws", popularity = "4.9%" }
        },
        TRINKET1 = {
            { id = 246344, name = "Cursed Stone Idol", popularity = "39.9%" },
            { id = 242395, name = "BiSAstral Antenna", popularity = "36.0%" },
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "31.2%" },
            { id = 242396, name = "Unyielding Netherprism", popularity = "11.3%" },
            { id = 190958, name = "So'leah's Secret Technique", popularity = "11.3%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "62.9%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "37.9%" },
            { id = 212265, name = "Tempered Potion", popularity = "62.5%" },
            { id = 222720, name = "The Sushi Special", popularity = "31.2%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "76.5%" }
        }
    },
    VENGEANCE = {
        icon = "Interface/ICONS/Ability_DemonHunter_SpecTank",
        talent = "CUkAAAAAAAAAAAAAAAAAAAAAAAAmZMmZMMjMzMMDzMbjxMsNDzMmZMY2mZmNzMmZYGAAAAmtZwwYZhJMYmhxC",
        statprio = "Haste > Crit > Mastery > Vers",
        enchants = {
            BACK = { id = 223737, name = "Chant of Leeching Fangs", popularity = "63.1%" },
            LEGS = { id = 219911, name = "Stormbound Armor Kit", popularity = "75.7%" },
            CHEST = { id = 223692, name = "Crystalline Radiance", popularity = "84.0%" },
            FEET = { id = 223656, name = "Defender's March", popularity = "64.7%" },
            WRIST = { id = 223719, name = "Chant of Armored Leech", popularity = "57.8%" },
            RINGS = { id = 223674, name = "Radiant Haste", popularity = "55.0%" },
            MAINHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "46.9%" },
            OFFHAND = { id = 223781, name = "Authority of Radiant Power", popularity = "43.9%" }
        },
        epic_gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "54.0%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "11.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.5%" }
        },
        gems = {
            { id = 213743, name = "Culminating Blasphemite", popularity = "54.0%" },
            { id = 213746, name = "Elusive Blasphemite", popularity = "11.5%" },
            { id = 217115, name = "Cubic Blasphemia", popularity = "0.5%" }
        },
        HEAD = {
            { id = 237691, name = "Charhound's Vicious Scalp", popularity = "57.1%" },
            { id = 234498, name = "Waterworks Filtration Mask", popularity = "15.4%" },
            { id = 237525, name = "BiSIrradiated Impurity Filter", popularity = "10.4%" },
            { id = 221125, name = "Helm of the Righteous Crusade", popularity = "3.9%" },
            { id = 219329, name = "Rune-Branded Hood", popularity = "2.5%" }
        },
        NECK = {
            { id = 185842, name = "BiSOrnately Engraved Amplifier", popularity = "34.3%" },
            { id = 185820, name = "Cabochon of the Infinite Flight", popularity = "21.3%" },
            { id = 215136, name = "Amulet of Earthen Craftsmanship", popularity = "14.0%" },
            { id = 178827, name = "Sin Stained Pendant", popularity = "7.4%" },
            { id = 252009, name = "Bloodstained Memento", popularity = "5.6%" }
        },
        SHOULDERS = {
            { id = 237689, name = "BiSCharhound's Vicious Hornguards", popularity = "84.7%" },
            { id = 242486, name = "Mantle of Wounded Fate", popularity = "3.7%" },
            { id = 229314, name = "Fel-Dealer's Recycled Reavers", popularity = "1.4%" },
            { id = 234500, name = "Mechanized Junkpads", popularity = "1.3%" },
            { id = 221148, name = "Epaulets of the Clipped Wings", popularity = "1.2%" }
        },
        BACK = {
            { id = 235499, name = "BiSReshii Wraps", popularity = "96.3%" }
        },
        CHEST = {
            { id = 237694, name = "BiSCharhound's Vicious Bindings", popularity = "87.8%" },
            { id = 221130, name = "Seraphic Wraps of the Ordained", popularity = "1.6%" },
            { id = 229319, name = "Fel-Dealer's Soul Engine", popularity = "1.4%" },
            { id = 246273, name = "Vest of Refracted Shadows", popularity = "0.9%" },
            { id = 237541, name = "Darksorrow's Corrupted Carapace", popularity = "0.9%" }
        },
        WRISTS = {
            { id = 219334, name = "BiSRune-Branded Armbands", popularity = "60.2%" },
            { id = 221142, name = "Scheming Assailer's Bands", popularity = "11.2%" },
            { id = 237546, name = "Bindings of Lost Essence", popularity = "5.5%" },
            { id = 221157, name = "Unbreakable Beetlebane Bindings", popularity = "4.8%" },
            { id = 234499, name = "Disturbed Kelp Wraps", popularity = "3.7%" }
        },
        HANDS = {
            { id = 237692, name = "BiSCharhound's Vicious Felclaws", popularity = "77.7%" },
            { id = 178832, name = "Gloves of Haunting Fixation", popularity = "5.9%" },
            { id = 229317, name = "Fel-Dealer's Underhandlers", popularity = "2.8%" },
            { id = 219333, name = "Rune-Branded Grasps", popularity = "2.4%" },
            { id = 185791, name = "Knuckle-Dusting Handwraps", popularity = "1.7%" }
        },
        WAIST = {
            { id = 245964, name = "Durable Information Securing Container", popularity = "41.2%" },
            { id = 219331, name = "Rune-Branded Waistband", popularity = "15.2%" },
            { id = 185809, name = "BiSVenza's Powderbelt", popularity = "13.7%" },
            { id = 219502, name = "Adrenal Surge Clasp", popularity = "8.4%" },
            { id = 221134, name = "Shadow Congregant's Belt", popularity = "5.1%" }
        },
        LEGS = {
            { id = 237690, name = "BiSCharhound's Vicious Hidecoat", popularity = "88.1%" },
            { id = 221153, name = "Gauzewoven Legguards", popularity = "1.4%" },
            { id = 219332, name = "Rune-Branded Legwraps", popularity = "1.2%" },
            { id = 185801, name = "Anomalous Starlit Breeches", popularity = "1.1%" },
            { id = 242473, name = "Spittle-Stained Trousers", popularity = "1.1%" }
        },
        FEET = {
            { id = 243306, name = "BiSInterloper's Reinforced Sandals", popularity = "36.0%" },
            { id = 246274, name = "Geezle's Zapstep Boots", popularity = "15.2%" },
            { id = 221120, name = "Stalwart Guardian's Boots", popularity = "10.0%" },
            { id = 246280, name = "Boots of Titanic Deconversion", popularity = "8.7%" },
            { id = 237553, name = "Laboratory Test Slippers", popularity = "7.2%" }
        },
        FINGER1 = {
            { id = 221136, name = "Devout Zealot's Ring", popularity = "39.9%" },
            { id = 246281, name = "BiSRing of the Panoply", popularity = "37.7%" },
            { id = 185813, name = "Signet of Collapsing Stars", popularity = "25.1%" },
            { id = 215135, name = "Ring of Earthen Craftsmanship", popularity = "24.3%" },
            { id = 242491, name = "Whispers of K'aresh", popularity = "11.4%" }
        },
        MAIN_HAND = {
            { id = 222441, name = "Everforged Warglaive", popularity = "29.2%" },
            { id = 222440, name = "BiSEverforged Longsword", popularity = "25.7%" },
            { id = 234491, name = "BiSSonic Ka-BOOM!-erang", popularity = "8.7%" },
            { id = 185778, name = "First Fist of the So Cartel", popularity = "8.0%" },
            { id = 237738, name = "Unbound Training Claws", popularity = "5.5%" }
        },
        OFF_HAND = {
            { id = 222441, name = "Everforged Warglaive", popularity = "30.3%" },
            { id = 222440, name = "BiSEverforged Longsword", popularity = "22.3%" },
            { id = 234491, name = "BiSSonic Ka-BOOM!-erang", popularity = "10.6%" },
            { id = 185778, name = "First Fist of the So Cartel", popularity = "7.1%" },
            { id = 221144, name = "Zephyrous Sail Carver", popularity = "4.1%" }
        },
        TRINKET1 = {
            { id = 232541, name = "Improvised Seaforium Pacemaker", popularity = "37.2%" },
            { id = 242401, name = "Brand of Ceaseless Ire", popularity = "34.5%" },
            { id = 190958, name = "BiSSo'leah's Secret Technique", popularity = "18.1%" },
            { id = 219309, name = "BiSTome of Light's Devotion", popularity = "17.2%" },
            { id = 242395, name = "Astral Antenna", popularity = "15.1%" }
        },
        consumables = {
            { id = 212283, name = "Flask of Alchemical Chaos", popularity = "33.5%" },
            { id = 244839, name = "Invigorating Healing Potion", popularity = "26.7%" },
            { id = 212265, name = "Tempered Potion", popularity = "30.0%" },
            { id = 222720, name = "The Sushi Special", popularity = "37.8%" },
            { id = 224107, name = "Algari Mana Oil", popularity = "67.6%" }
        }
    }
}
