name: Auto Release to CurseForge

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Addon
        run: |
          cd ..
          zip -r NemLootTracker.zip NemLootTracker

      - name: Upload to CurseForge
        uses: BigWigsMods/packager@v2 